// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mixer_mixer_Pipeline_VITIS_LOOP_30_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stream_in_0_TVALID,
        stream_in_1_TVALID,
        stream_in_2_TVALID,
        stream_in_3_TVALID,
        stream_in_4_TVALID,
        stream_in_5_TVALID,
        stream_in_6_TVALID,
        stream_in_7_TVALID,
        mix_out_TREADY,
        active_14,
        mix_out_TDATA,
        mix_out_TVALID,
        mix_out_TKEEP,
        mix_out_TSTRB,
        mix_out_TUSER,
        mix_out_TLAST,
        mix_out_TID,
        mix_out_TDEST,
        stream_in_0_TDATA,
        stream_in_0_TREADY,
        stream_in_0_TKEEP,
        stream_in_0_TSTRB,
        stream_in_0_TUSER,
        stream_in_0_TLAST,
        stream_in_0_TID,
        stream_in_0_TDEST,
        stream_in_1_TDATA,
        stream_in_1_TREADY,
        stream_in_1_TKEEP,
        stream_in_1_TSTRB,
        stream_in_1_TUSER,
        stream_in_1_TLAST,
        stream_in_1_TID,
        stream_in_1_TDEST,
        stream_in_2_TDATA,
        stream_in_2_TREADY,
        stream_in_2_TKEEP,
        stream_in_2_TSTRB,
        stream_in_2_TUSER,
        stream_in_2_TLAST,
        stream_in_2_TID,
        stream_in_2_TDEST,
        stream_in_3_TDATA,
        stream_in_3_TREADY,
        stream_in_3_TKEEP,
        stream_in_3_TSTRB,
        stream_in_3_TUSER,
        stream_in_3_TLAST,
        stream_in_3_TID,
        stream_in_3_TDEST,
        stream_in_4_TDATA,
        stream_in_4_TREADY,
        stream_in_4_TKEEP,
        stream_in_4_TSTRB,
        stream_in_4_TUSER,
        stream_in_4_TLAST,
        stream_in_4_TID,
        stream_in_4_TDEST,
        stream_in_5_TDATA,
        stream_in_5_TREADY,
        stream_in_5_TKEEP,
        stream_in_5_TSTRB,
        stream_in_5_TUSER,
        stream_in_5_TLAST,
        stream_in_5_TID,
        stream_in_5_TDEST,
        stream_in_6_TDATA,
        stream_in_6_TREADY,
        stream_in_6_TKEEP,
        stream_in_6_TSTRB,
        stream_in_6_TUSER,
        stream_in_6_TLAST,
        stream_in_6_TID,
        stream_in_6_TDEST,
        stream_in_7_TDATA,
        stream_in_7_TREADY,
        stream_in_7_TKEEP,
        stream_in_7_TSTRB,
        stream_in_7_TUSER,
        stream_in_7_TLAST,
        stream_in_7_TID,
        stream_in_7_TDEST,
        empty_16,
        empty_17,
        empty_18,
        empty_19,
        empty_20,
        empty_21,
        empty_22,
        empty,
        out_pkt_data_out,
        out_pkt_data_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   stream_in_0_TVALID;
input   stream_in_1_TVALID;
input   stream_in_2_TVALID;
input   stream_in_3_TVALID;
input   stream_in_4_TVALID;
input   stream_in_5_TVALID;
input   stream_in_6_TVALID;
input   stream_in_7_TVALID;
input   mix_out_TREADY;
input  [3:0] active_14;
output  [31:0] mix_out_TDATA;
output   mix_out_TVALID;
output  [3:0] mix_out_TKEEP;
output  [3:0] mix_out_TSTRB;
output  [1:0] mix_out_TUSER;
output  [0:0] mix_out_TLAST;
output  [4:0] mix_out_TID;
output  [5:0] mix_out_TDEST;
input  [31:0] stream_in_0_TDATA;
output   stream_in_0_TREADY;
input  [3:0] stream_in_0_TKEEP;
input  [3:0] stream_in_0_TSTRB;
input  [1:0] stream_in_0_TUSER;
input  [0:0] stream_in_0_TLAST;
input  [4:0] stream_in_0_TID;
input  [5:0] stream_in_0_TDEST;
input  [31:0] stream_in_1_TDATA;
output   stream_in_1_TREADY;
input  [3:0] stream_in_1_TKEEP;
input  [3:0] stream_in_1_TSTRB;
input  [1:0] stream_in_1_TUSER;
input  [0:0] stream_in_1_TLAST;
input  [4:0] stream_in_1_TID;
input  [5:0] stream_in_1_TDEST;
input  [31:0] stream_in_2_TDATA;
output   stream_in_2_TREADY;
input  [3:0] stream_in_2_TKEEP;
input  [3:0] stream_in_2_TSTRB;
input  [1:0] stream_in_2_TUSER;
input  [0:0] stream_in_2_TLAST;
input  [4:0] stream_in_2_TID;
input  [5:0] stream_in_2_TDEST;
input  [31:0] stream_in_3_TDATA;
output   stream_in_3_TREADY;
input  [3:0] stream_in_3_TKEEP;
input  [3:0] stream_in_3_TSTRB;
input  [1:0] stream_in_3_TUSER;
input  [0:0] stream_in_3_TLAST;
input  [4:0] stream_in_3_TID;
input  [5:0] stream_in_3_TDEST;
input  [31:0] stream_in_4_TDATA;
output   stream_in_4_TREADY;
input  [3:0] stream_in_4_TKEEP;
input  [3:0] stream_in_4_TSTRB;
input  [1:0] stream_in_4_TUSER;
input  [0:0] stream_in_4_TLAST;
input  [4:0] stream_in_4_TID;
input  [5:0] stream_in_4_TDEST;
input  [31:0] stream_in_5_TDATA;
output   stream_in_5_TREADY;
input  [3:0] stream_in_5_TKEEP;
input  [3:0] stream_in_5_TSTRB;
input  [1:0] stream_in_5_TUSER;
input  [0:0] stream_in_5_TLAST;
input  [4:0] stream_in_5_TID;
input  [5:0] stream_in_5_TDEST;
input  [31:0] stream_in_6_TDATA;
output   stream_in_6_TREADY;
input  [3:0] stream_in_6_TKEEP;
input  [3:0] stream_in_6_TSTRB;
input  [1:0] stream_in_6_TUSER;
input  [0:0] stream_in_6_TLAST;
input  [4:0] stream_in_6_TID;
input  [5:0] stream_in_6_TDEST;
input  [31:0] stream_in_7_TDATA;
output   stream_in_7_TREADY;
input  [3:0] stream_in_7_TKEEP;
input  [3:0] stream_in_7_TSTRB;
input  [1:0] stream_in_7_TUSER;
input  [0:0] stream_in_7_TLAST;
input  [4:0] stream_in_7_TID;
input  [5:0] stream_in_7_TDEST;
input  [0:0] empty_16;
input  [0:0] empty_17;
input  [0:0] empty_18;
input  [0:0] empty_19;
input  [0:0] empty_20;
input  [0:0] empty_21;
input  [0:0] empty_22;
input  [0:0] empty;
output  [31:0] out_pkt_data_out;
output   out_pkt_data_out_ap_vld;

reg ap_idle;
reg mix_out_TVALID;
reg stream_in_0_TREADY;
reg stream_in_1_TREADY;
reg stream_in_2_TREADY;
reg stream_in_3_TREADY;
reg stream_in_4_TREADY;
reg stream_in_5_TREADY;
reg stream_in_6_TREADY;
reg stream_in_7_TREADY;
reg out_pkt_data_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg;
reg    ap_block_pp0_stage0_subdone_grp1;
reg    ap_block_pp0_stage0_subdone;
reg   [0:0] or_ln69_6_reg_830;
reg   [0:0] or_ln69_6_reg_830_pp0_iter1_reg;
reg    ap_block_state3_pp0_stage0_iter2_grp1;
wire   [0:0] or_ln69_6_fu_659_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    mix_out_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    stream_in_0_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    stream_in_1_TDATA_blk_n;
reg    stream_in_2_TDATA_blk_n;
reg    stream_in_3_TDATA_blk_n;
reg    stream_in_4_TDATA_blk_n;
reg    stream_in_5_TDATA_blk_n;
reg    stream_in_6_TDATA_blk_n;
reg    stream_in_7_TDATA_blk_n;
reg   [31:0] out_pkt_data_reg_484;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [0:0] icmp_ln65_fu_501_p2;
reg   [0:0] icmp_ln65_reg_805;
reg   [31:0] empty_32_reg_809_0;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] empty_33_reg_814_0;
reg   [31:0] empty_34_reg_819_0;
wire   [31:0] mix_int_8_fu_615_p3;
reg   [31:0] mix_int_8_reg_824;
wire   [31:0] mix_int_14_fu_704_p3;
reg  signed [31:0] mix_int_14_reg_834;
reg   [31:0] ap_phi_mux_out_pkt_data_phi_fu_488_p4;
reg   [31:0] ap_phi_reg_pp0_iter2_out_pkt_data_reg_484;
wire   [31:0] ap_phi_reg_pp0_iter0_out_pkt_data_reg_484;
reg   [31:0] ap_phi_reg_pp0_iter1_out_pkt_data_reg_484;
reg    ap_block_pp0_stage0_01001_grp1;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
wire   [8:0] mul_ln65_fu_497_p0;
wire   [31:0] mix_int_fu_559_p3;
wire   [31:0] mix_int_1_fu_567_p2;
wire   [31:0] mix_int_2_fu_573_p3;
wire   [31:0] mix_int_3_fu_581_p2;
wire   [31:0] mix_int_4_fu_587_p3;
wire   [31:0] mix_int_5_fu_595_p2;
wire   [31:0] mix_int_6_fu_601_p3;
wire   [31:0] mix_int_7_fu_609_p2;
wire   [0:0] or_ln69_1_fu_629_p2;
wire   [0:0] or_ln69_fu_623_p2;
wire   [0:0] or_ln69_4_fu_647_p2;
wire   [0:0] or_ln69_3_fu_641_p2;
wire   [0:0] or_ln69_5_fu_653_p2;
wire   [0:0] or_ln69_2_fu_635_p2;
wire   [31:0] mix_int_9_fu_674_p2;
wire   [31:0] mix_int_10_fu_679_p3;
wire   [31:0] mix_int_11_fu_685_p2;
wire   [31:0] mix_int_12_fu_691_p3;
wire   [31:0] mix_int_13_fu_698_p2;
wire   [8:0] zext_ln65_cast_fu_715_p17;
wire   [8:0] zext_ln65_cast_fu_715_p19;
wire   [39:0] mul_ln65_fu_497_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_loop_init;
wire   [39:0] mul_ln65_fu_497_p00;
reg    ap_condition_283;
wire   [3:0] zext_ln65_cast_fu_715_p1;
wire   [3:0] zext_ln65_cast_fu_715_p3;
wire   [3:0] zext_ln65_cast_fu_715_p5;
wire   [3:0] zext_ln65_cast_fu_715_p7;
wire   [3:0] zext_ln65_cast_fu_715_p9;
wire   [3:0] zext_ln65_cast_fu_715_p11;
wire   [3:0] zext_ln65_cast_fu_715_p13;
wire  signed [3:0] zext_ln65_cast_fu_715_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

mixer_mul_9ns_32s_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 40 ))
mul_9ns_32s_40_1_1_U1(
    .din0(mul_ln65_fu_497_p0),
    .din1(mix_int_14_reg_834),
    .dout(mul_ln65_fu_497_p2)
);

(* dissolve_hierarchy = "yes" *) mixer_sparsemux_17_4_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h1 ),
    .din0_WIDTH( 9 ),
    .CASE1( 4'h2 ),
    .din1_WIDTH( 9 ),
    .CASE2( 4'h3 ),
    .din2_WIDTH( 9 ),
    .CASE3( 4'h4 ),
    .din3_WIDTH( 9 ),
    .CASE4( 4'h5 ),
    .din4_WIDTH( 9 ),
    .CASE5( 4'h6 ),
    .din5_WIDTH( 9 ),
    .CASE6( 4'h7 ),
    .din6_WIDTH( 9 ),
    .CASE7( 4'h8 ),
    .din7_WIDTH( 9 ),
    .def_WIDTH( 9 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 9 ))
sparsemux_17_4_9_1_1_U2(
    .din0(9'd256),
    .din1(9'd181),
    .din2(9'd148),
    .din3(9'd128),
    .din4(9'd114),
    .din5(9'd105),
    .din6(9'd97),
    .din7(9'd91),
    .def(zext_ln65_cast_fu_715_p17),
    .sel(active_14),
    .dout(zext_ln65_cast_fu_715_p19)
);

mixer_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_283)) begin
        if ((icmp_ln65_fu_501_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_out_pkt_data_reg_484 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_out_pkt_data_reg_484 <= ap_phi_reg_pp0_iter0_out_pkt_data_reg_484;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln65_reg_805 == 1'd0))) begin
        out_pkt_data_reg_484 <= {{mul_ln65_fu_497_p2[39:8]}};
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~(or_ln69_6_reg_830_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        out_pkt_data_reg_484 <= ap_phi_reg_pp0_iter2_out_pkt_data_reg_484;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        empty_32_reg_809_0 <= stream_in_5_TDATA;
        empty_33_reg_814_0 <= stream_in_6_TDATA;
        empty_34_reg_819_0 <= stream_in_7_TDATA;
        mix_int_8_reg_824 <= mix_int_8_fu_615_p3;
        or_ln69_6_reg_830 <= or_ln69_6_fu_659_p2;
        or_ln69_6_reg_830_pp0_iter1_reg <= or_ln69_6_reg_830;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_out_pkt_data_reg_484 <= ap_phi_reg_pp0_iter1_out_pkt_data_reg_484;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln65_reg_805 <= icmp_ln65_fu_501_p2;
        mix_int_14_reg_834 <= mix_int_14_fu_704_p3;
    end
end

always @ (*) begin
    if (((or_ln69_6_fu_659_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln65_reg_805 == 1'd0)) begin
        ap_phi_mux_out_pkt_data_phi_fu_488_p4 = {{mul_ln65_fu_497_p2[39:8]}};
    end else begin
        ap_phi_mux_out_pkt_data_phi_fu_488_p4 = ap_phi_reg_pp0_iter2_out_pkt_data_reg_484;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln69_6_reg_830_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        mix_out_TDATA_blk_n = mix_out_TREADY;
    end else begin
        mix_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_ln69_6_reg_830_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        mix_out_TVALID = 1'b1;
    end else begin
        mix_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln69_6_reg_830_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        out_pkt_data_out_ap_vld = 1'b1;
    end else begin
        out_pkt_data_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_0_TDATA_blk_n = stream_in_0_TVALID;
    end else begin
        stream_in_0_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_0_TREADY = 1'b1;
    end else begin
        stream_in_0_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_1_TDATA_blk_n = stream_in_1_TVALID;
    end else begin
        stream_in_1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_1_TREADY = 1'b1;
    end else begin
        stream_in_1_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_2_TDATA_blk_n = stream_in_2_TVALID;
    end else begin
        stream_in_2_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_2_TREADY = 1'b1;
    end else begin
        stream_in_2_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_3_TDATA_blk_n = stream_in_3_TVALID;
    end else begin
        stream_in_3_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_3_TREADY = 1'b1;
    end else begin
        stream_in_3_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_4_TDATA_blk_n = stream_in_4_TVALID;
    end else begin
        stream_in_4_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_4_TREADY = 1'b1;
    end else begin
        stream_in_4_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_5_TDATA_blk_n = stream_in_5_TVALID;
    end else begin
        stream_in_5_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_5_TREADY = 1'b1;
    end else begin
        stream_in_5_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_6_TDATA_blk_n = stream_in_6_TVALID;
    end else begin
        stream_in_6_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_6_TREADY = 1'b1;
    end else begin
        stream_in_6_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_7_TDATA_blk_n = stream_in_7_TVALID;
    end else begin
        stream_in_7_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_7_TREADY = 1'b1;
    end else begin
        stream_in_7_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_start_int == 1'b1) & ((stream_in_7_TVALID == 1'b0) | (stream_in_6_TVALID == 1'b0) | (stream_in_5_TVALID == 1'b0) | (stream_in_4_TVALID == 1'b0) | (stream_in_3_TVALID == 1'b0) | (stream_in_2_TVALID == 1'b0) | (stream_in_1_TVALID == 1'b0) | (stream_in_0_TVALID == 1'b0))) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_start_int == 1'b1) & ((stream_in_7_TVALID == 1'b0) | (stream_in_6_TVALID == 1'b0) | (stream_in_5_TVALID == 1'b0) | (stream_in_4_TVALID == 1'b0) | (stream_in_3_TVALID == 1'b0) | (stream_in_2_TVALID == 1'b0) | (stream_in_1_TVALID == 1'b0) | (stream_in_0_TVALID == 1'b0))) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp1 = ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2_grp1 = ((or_ln69_6_reg_830_pp0_iter1_reg == 1'd0) & (mix_out_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_283 = ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_out_pkt_data_reg_484 = 'bx;

assign ap_ready = ap_ready_sig;

assign icmp_ln65_fu_501_p2 = ((active_14 == 4'd0) ? 1'b1 : 1'b0);

assign mix_int_10_fu_679_p3 = ((empty_21[0:0] == 1'b1) ? mix_int_9_fu_674_p2 : mix_int_8_reg_824);

assign mix_int_11_fu_685_p2 = (empty_33_reg_814_0 + mix_int_10_fu_679_p3);

assign mix_int_12_fu_691_p3 = ((empty_22[0:0] == 1'b1) ? mix_int_11_fu_685_p2 : mix_int_10_fu_679_p3);

assign mix_int_13_fu_698_p2 = (empty_34_reg_819_0 + mix_int_12_fu_691_p3);

assign mix_int_14_fu_704_p3 = ((empty[0:0] == 1'b1) ? mix_int_13_fu_698_p2 : mix_int_12_fu_691_p3);

assign mix_int_1_fu_567_p2 = (stream_in_1_TDATA + mix_int_fu_559_p3);

assign mix_int_2_fu_573_p3 = ((empty_17[0:0] == 1'b1) ? mix_int_1_fu_567_p2 : mix_int_fu_559_p3);

assign mix_int_3_fu_581_p2 = (stream_in_2_TDATA + mix_int_2_fu_573_p3);

assign mix_int_4_fu_587_p3 = ((empty_18[0:0] == 1'b1) ? mix_int_3_fu_581_p2 : mix_int_2_fu_573_p3);

assign mix_int_5_fu_595_p2 = (stream_in_3_TDATA + mix_int_4_fu_587_p3);

assign mix_int_6_fu_601_p3 = ((empty_19[0:0] == 1'b1) ? mix_int_5_fu_595_p2 : mix_int_4_fu_587_p3);

assign mix_int_7_fu_609_p2 = (stream_in_4_TDATA + mix_int_6_fu_601_p3);

assign mix_int_8_fu_615_p3 = ((empty_20[0:0] == 1'b1) ? mix_int_7_fu_609_p2 : mix_int_6_fu_601_p3);

assign mix_int_9_fu_674_p2 = (empty_32_reg_809_0 + mix_int_8_reg_824);

assign mix_int_fu_559_p3 = ((empty_16[0:0] == 1'b1) ? stream_in_0_TDATA : 32'd0);

assign mix_out_TDATA = ap_phi_mux_out_pkt_data_phi_fu_488_p4;

assign mix_out_TDEST = 6'd0;

assign mix_out_TID = 5'd0;

assign mix_out_TKEEP = 4'd15;

assign mix_out_TLAST = 1'd0;

assign mix_out_TSTRB = 4'd15;

assign mix_out_TUSER = 2'd0;

assign mul_ln65_fu_497_p0 = mul_ln65_fu_497_p00;

assign mul_ln65_fu_497_p00 = zext_ln65_cast_fu_715_p19;

assign or_ln69_1_fu_629_p2 = (stream_in_5_TLAST | stream_in_4_TLAST);

assign or_ln69_2_fu_635_p2 = (or_ln69_fu_623_p2 | or_ln69_1_fu_629_p2);

assign or_ln69_3_fu_641_p2 = (stream_in_1_TLAST | stream_in_0_TLAST);

assign or_ln69_4_fu_647_p2 = (stream_in_3_TLAST | stream_in_2_TLAST);

assign or_ln69_5_fu_653_p2 = (or_ln69_4_fu_647_p2 | or_ln69_3_fu_641_p2);

assign or_ln69_6_fu_659_p2 = (or_ln69_5_fu_653_p2 | or_ln69_2_fu_635_p2);

assign or_ln69_fu_623_p2 = (stream_in_7_TLAST | stream_in_6_TLAST);

assign out_pkt_data_out = out_pkt_data_reg_484;

assign zext_ln65_cast_fu_715_p17 = 'bx;

endmodule //mixer_mixer_Pipeline_VITIS_LOOP_30_1
