// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mixer_mixer,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sfvc784-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.388000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=374,HLS_SYN_LUT=1106,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module mixer (
        ap_clk,
        ap_rst_n,
        stream_in_0_TDATA,
        stream_in_0_TVALID,
        stream_in_0_TREADY,
        stream_in_0_TKEEP,
        stream_in_0_TSTRB,
        stream_in_0_TUSER,
        stream_in_0_TLAST,
        stream_in_0_TID,
        stream_in_0_TDEST,
        stream_in_1_TDATA,
        stream_in_1_TVALID,
        stream_in_1_TREADY,
        stream_in_1_TKEEP,
        stream_in_1_TSTRB,
        stream_in_1_TUSER,
        stream_in_1_TLAST,
        stream_in_1_TID,
        stream_in_1_TDEST,
        stream_in_2_TDATA,
        stream_in_2_TVALID,
        stream_in_2_TREADY,
        stream_in_2_TKEEP,
        stream_in_2_TSTRB,
        stream_in_2_TUSER,
        stream_in_2_TLAST,
        stream_in_2_TID,
        stream_in_2_TDEST,
        stream_in_3_TDATA,
        stream_in_3_TVALID,
        stream_in_3_TREADY,
        stream_in_3_TKEEP,
        stream_in_3_TSTRB,
        stream_in_3_TUSER,
        stream_in_3_TLAST,
        stream_in_3_TID,
        stream_in_3_TDEST,
        stream_in_4_TDATA,
        stream_in_4_TVALID,
        stream_in_4_TREADY,
        stream_in_4_TKEEP,
        stream_in_4_TSTRB,
        stream_in_4_TUSER,
        stream_in_4_TLAST,
        stream_in_4_TID,
        stream_in_4_TDEST,
        stream_in_5_TDATA,
        stream_in_5_TVALID,
        stream_in_5_TREADY,
        stream_in_5_TKEEP,
        stream_in_5_TSTRB,
        stream_in_5_TUSER,
        stream_in_5_TLAST,
        stream_in_5_TID,
        stream_in_5_TDEST,
        stream_in_6_TDATA,
        stream_in_6_TVALID,
        stream_in_6_TREADY,
        stream_in_6_TKEEP,
        stream_in_6_TSTRB,
        stream_in_6_TUSER,
        stream_in_6_TLAST,
        stream_in_6_TID,
        stream_in_6_TDEST,
        stream_in_7_TDATA,
        stream_in_7_TVALID,
        stream_in_7_TREADY,
        stream_in_7_TKEEP,
        stream_in_7_TSTRB,
        stream_in_7_TUSER,
        stream_in_7_TLAST,
        stream_in_7_TID,
        stream_in_7_TDEST,
        switches,
        mix_out_TDATA,
        mix_out_TVALID,
        mix_out_TREADY,
        mix_out_TKEEP,
        mix_out_TSTRB,
        mix_out_TUSER,
        mix_out_TLAST,
        mix_out_TID,
        mix_out_TDEST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] stream_in_0_TDATA;
input   stream_in_0_TVALID;
output   stream_in_0_TREADY;
input  [3:0] stream_in_0_TKEEP;
input  [3:0] stream_in_0_TSTRB;
input  [1:0] stream_in_0_TUSER;
input  [0:0] stream_in_0_TLAST;
input  [4:0] stream_in_0_TID;
input  [5:0] stream_in_0_TDEST;
input  [31:0] stream_in_1_TDATA;
input   stream_in_1_TVALID;
output   stream_in_1_TREADY;
input  [3:0] stream_in_1_TKEEP;
input  [3:0] stream_in_1_TSTRB;
input  [1:0] stream_in_1_TUSER;
input  [0:0] stream_in_1_TLAST;
input  [4:0] stream_in_1_TID;
input  [5:0] stream_in_1_TDEST;
input  [31:0] stream_in_2_TDATA;
input   stream_in_2_TVALID;
output   stream_in_2_TREADY;
input  [3:0] stream_in_2_TKEEP;
input  [3:0] stream_in_2_TSTRB;
input  [1:0] stream_in_2_TUSER;
input  [0:0] stream_in_2_TLAST;
input  [4:0] stream_in_2_TID;
input  [5:0] stream_in_2_TDEST;
input  [31:0] stream_in_3_TDATA;
input   stream_in_3_TVALID;
output   stream_in_3_TREADY;
input  [3:0] stream_in_3_TKEEP;
input  [3:0] stream_in_3_TSTRB;
input  [1:0] stream_in_3_TUSER;
input  [0:0] stream_in_3_TLAST;
input  [4:0] stream_in_3_TID;
input  [5:0] stream_in_3_TDEST;
input  [31:0] stream_in_4_TDATA;
input   stream_in_4_TVALID;
output   stream_in_4_TREADY;
input  [3:0] stream_in_4_TKEEP;
input  [3:0] stream_in_4_TSTRB;
input  [1:0] stream_in_4_TUSER;
input  [0:0] stream_in_4_TLAST;
input  [4:0] stream_in_4_TID;
input  [5:0] stream_in_4_TDEST;
input  [31:0] stream_in_5_TDATA;
input   stream_in_5_TVALID;
output   stream_in_5_TREADY;
input  [3:0] stream_in_5_TKEEP;
input  [3:0] stream_in_5_TSTRB;
input  [1:0] stream_in_5_TUSER;
input  [0:0] stream_in_5_TLAST;
input  [4:0] stream_in_5_TID;
input  [5:0] stream_in_5_TDEST;
input  [31:0] stream_in_6_TDATA;
input   stream_in_6_TVALID;
output   stream_in_6_TREADY;
input  [3:0] stream_in_6_TKEEP;
input  [3:0] stream_in_6_TSTRB;
input  [1:0] stream_in_6_TUSER;
input  [0:0] stream_in_6_TLAST;
input  [4:0] stream_in_6_TID;
input  [5:0] stream_in_6_TDEST;
input  [31:0] stream_in_7_TDATA;
input   stream_in_7_TVALID;
output   stream_in_7_TREADY;
input  [3:0] stream_in_7_TKEEP;
input  [3:0] stream_in_7_TSTRB;
input  [1:0] stream_in_7_TUSER;
input  [0:0] stream_in_7_TLAST;
input  [4:0] stream_in_7_TID;
input  [5:0] stream_in_7_TDEST;
input  [7:0] switches;
output  [31:0] mix_out_TDATA;
output   mix_out_TVALID;
input   mix_out_TREADY;
output  [3:0] mix_out_TKEEP;
output  [3:0] mix_out_TSTRB;
output  [1:0] mix_out_TUSER;
output  [0:0] mix_out_TLAST;
output  [4:0] mix_out_TID;
output  [5:0] mix_out_TDEST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg    mix_out_TDATA_blk_n;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [0:0] trunc_ln54_fu_395_p1;
reg   [0:0] trunc_ln54_reg_577;
wire   [0:0] tmp_fu_399_p3;
reg   [0:0] tmp_reg_582;
wire   [0:0] tmp_8_fu_407_p3;
reg   [0:0] tmp_8_reg_587;
wire   [0:0] tmp_9_fu_415_p3;
reg   [0:0] tmp_9_reg_592;
wire   [0:0] tmp_10_fu_423_p3;
reg   [0:0] tmp_10_reg_597;
wire   [0:0] tmp_11_fu_431_p3;
reg   [0:0] tmp_11_reg_602;
wire   [0:0] tmp_12_fu_439_p3;
reg   [0:0] tmp_12_reg_607;
wire   [0:0] tmp_13_fu_447_p3;
reg   [0:0] tmp_13_reg_612;
wire   [3:0] select_ln61_fu_559_p3;
reg   [3:0] select_ln61_reg_617;
wire    grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_ap_start;
wire    grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_ap_done;
wire    grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_ap_idle;
wire    grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_ap_ready;
wire    grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TREADY;
wire   [31:0] grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TDATA;
wire    grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TVALID;
wire   [3:0] grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TKEEP;
wire   [3:0] grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TSTRB;
wire   [1:0] grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TUSER;
wire   [0:0] grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TLAST;
wire   [4:0] grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TID;
wire   [5:0] grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TDEST;
wire    grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_0_TREADY;
wire    grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_1_TREADY;
wire    grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_2_TREADY;
wire    grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_3_TREADY;
wire    grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_4_TREADY;
wire    grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_5_TREADY;
wire    grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_6_TREADY;
wire    grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_7_TREADY;
wire   [31:0] grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_out_pkt_data_out;
wire    grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_out_pkt_data_out_ap_vld;
reg    grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg   [31:0] mix_out_TDATA_reg;
reg   [3:0] mix_out_TKEEP_reg;
reg   [3:0] mix_out_TSTRB_reg;
reg   [1:0] mix_out_TUSER_reg;
reg   [0:0] mix_out_TLAST_reg;
reg   [4:0] mix_out_TID_reg;
reg   [5:0] mix_out_TDEST_reg;
wire   [1:0] select_ln55_fu_459_p3;
wire   [1:0] zext_ln55_fu_455_p1;
wire   [1:0] select_ln55_1_fu_467_p3;
wire   [1:0] add_ln56_fu_475_p2;
wire   [1:0] select_ln56_fu_481_p3;
wire   [2:0] zext_ln57_fu_489_p1;
wire   [2:0] add_ln57_fu_493_p2;
wire   [2:0] select_ln57_fu_499_p3;
wire   [2:0] add_ln58_fu_507_p2;
wire   [2:0] select_ln58_fu_513_p3;
wire   [2:0] add_ln59_fu_521_p2;
wire   [2:0] select_ln59_fu_527_p3;
wire   [2:0] add_ln60_fu_535_p2;
wire   [2:0] select_ln60_fu_541_p3;
wire   [3:0] zext_ln61_fu_549_p1;
wire   [3:0] add_ln61_fu_553_p2;
wire    regslice_both_mix_out_V_data_V_U_apdone_blk;
reg    ap_block_state5;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    regslice_both_stream_in_0_V_data_V_U_apdone_blk;
wire   [31:0] stream_in_0_TDATA_int_regslice;
wire    stream_in_0_TVALID_int_regslice;
reg    stream_in_0_TREADY_int_regslice;
wire    regslice_both_stream_in_0_V_data_V_U_ack_in;
wire    regslice_both_stream_in_0_V_keep_V_U_apdone_blk;
wire   [3:0] stream_in_0_TKEEP_int_regslice;
wire    regslice_both_stream_in_0_V_keep_V_U_vld_out;
wire    regslice_both_stream_in_0_V_keep_V_U_ack_in;
wire    regslice_both_stream_in_0_V_strb_V_U_apdone_blk;
wire   [3:0] stream_in_0_TSTRB_int_regslice;
wire    regslice_both_stream_in_0_V_strb_V_U_vld_out;
wire    regslice_both_stream_in_0_V_strb_V_U_ack_in;
wire    regslice_both_stream_in_0_V_user_V_U_apdone_blk;
wire   [1:0] stream_in_0_TUSER_int_regslice;
wire    regslice_both_stream_in_0_V_user_V_U_vld_out;
wire    regslice_both_stream_in_0_V_user_V_U_ack_in;
wire    regslice_both_stream_in_0_V_last_V_U_apdone_blk;
wire   [0:0] stream_in_0_TLAST_int_regslice;
wire    regslice_both_stream_in_0_V_last_V_U_vld_out;
wire    regslice_both_stream_in_0_V_last_V_U_ack_in;
wire    regslice_both_stream_in_0_V_id_V_U_apdone_blk;
wire   [4:0] stream_in_0_TID_int_regslice;
wire    regslice_both_stream_in_0_V_id_V_U_vld_out;
wire    regslice_both_stream_in_0_V_id_V_U_ack_in;
wire    regslice_both_stream_in_0_V_dest_V_U_apdone_blk;
wire   [5:0] stream_in_0_TDEST_int_regslice;
wire    regslice_both_stream_in_0_V_dest_V_U_vld_out;
wire    regslice_both_stream_in_0_V_dest_V_U_ack_in;
wire    regslice_both_stream_in_1_V_data_V_U_apdone_blk;
wire   [31:0] stream_in_1_TDATA_int_regslice;
wire    stream_in_1_TVALID_int_regslice;
reg    stream_in_1_TREADY_int_regslice;
wire    regslice_both_stream_in_1_V_data_V_U_ack_in;
wire    regslice_both_stream_in_1_V_keep_V_U_apdone_blk;
wire   [3:0] stream_in_1_TKEEP_int_regslice;
wire    regslice_both_stream_in_1_V_keep_V_U_vld_out;
wire    regslice_both_stream_in_1_V_keep_V_U_ack_in;
wire    regslice_both_stream_in_1_V_strb_V_U_apdone_blk;
wire   [3:0] stream_in_1_TSTRB_int_regslice;
wire    regslice_both_stream_in_1_V_strb_V_U_vld_out;
wire    regslice_both_stream_in_1_V_strb_V_U_ack_in;
wire    regslice_both_stream_in_1_V_user_V_U_apdone_blk;
wire   [1:0] stream_in_1_TUSER_int_regslice;
wire    regslice_both_stream_in_1_V_user_V_U_vld_out;
wire    regslice_both_stream_in_1_V_user_V_U_ack_in;
wire    regslice_both_stream_in_1_V_last_V_U_apdone_blk;
wire   [0:0] stream_in_1_TLAST_int_regslice;
wire    regslice_both_stream_in_1_V_last_V_U_vld_out;
wire    regslice_both_stream_in_1_V_last_V_U_ack_in;
wire    regslice_both_stream_in_1_V_id_V_U_apdone_blk;
wire   [4:0] stream_in_1_TID_int_regslice;
wire    regslice_both_stream_in_1_V_id_V_U_vld_out;
wire    regslice_both_stream_in_1_V_id_V_U_ack_in;
wire    regslice_both_stream_in_1_V_dest_V_U_apdone_blk;
wire   [5:0] stream_in_1_TDEST_int_regslice;
wire    regslice_both_stream_in_1_V_dest_V_U_vld_out;
wire    regslice_both_stream_in_1_V_dest_V_U_ack_in;
wire    regslice_both_stream_in_2_V_data_V_U_apdone_blk;
wire   [31:0] stream_in_2_TDATA_int_regslice;
wire    stream_in_2_TVALID_int_regslice;
reg    stream_in_2_TREADY_int_regslice;
wire    regslice_both_stream_in_2_V_data_V_U_ack_in;
wire    regslice_both_stream_in_2_V_keep_V_U_apdone_blk;
wire   [3:0] stream_in_2_TKEEP_int_regslice;
wire    regslice_both_stream_in_2_V_keep_V_U_vld_out;
wire    regslice_both_stream_in_2_V_keep_V_U_ack_in;
wire    regslice_both_stream_in_2_V_strb_V_U_apdone_blk;
wire   [3:0] stream_in_2_TSTRB_int_regslice;
wire    regslice_both_stream_in_2_V_strb_V_U_vld_out;
wire    regslice_both_stream_in_2_V_strb_V_U_ack_in;
wire    regslice_both_stream_in_2_V_user_V_U_apdone_blk;
wire   [1:0] stream_in_2_TUSER_int_regslice;
wire    regslice_both_stream_in_2_V_user_V_U_vld_out;
wire    regslice_both_stream_in_2_V_user_V_U_ack_in;
wire    regslice_both_stream_in_2_V_last_V_U_apdone_blk;
wire   [0:0] stream_in_2_TLAST_int_regslice;
wire    regslice_both_stream_in_2_V_last_V_U_vld_out;
wire    regslice_both_stream_in_2_V_last_V_U_ack_in;
wire    regslice_both_stream_in_2_V_id_V_U_apdone_blk;
wire   [4:0] stream_in_2_TID_int_regslice;
wire    regslice_both_stream_in_2_V_id_V_U_vld_out;
wire    regslice_both_stream_in_2_V_id_V_U_ack_in;
wire    regslice_both_stream_in_2_V_dest_V_U_apdone_blk;
wire   [5:0] stream_in_2_TDEST_int_regslice;
wire    regslice_both_stream_in_2_V_dest_V_U_vld_out;
wire    regslice_both_stream_in_2_V_dest_V_U_ack_in;
wire    regslice_both_stream_in_3_V_data_V_U_apdone_blk;
wire   [31:0] stream_in_3_TDATA_int_regslice;
wire    stream_in_3_TVALID_int_regslice;
reg    stream_in_3_TREADY_int_regslice;
wire    regslice_both_stream_in_3_V_data_V_U_ack_in;
wire    regslice_both_stream_in_3_V_keep_V_U_apdone_blk;
wire   [3:0] stream_in_3_TKEEP_int_regslice;
wire    regslice_both_stream_in_3_V_keep_V_U_vld_out;
wire    regslice_both_stream_in_3_V_keep_V_U_ack_in;
wire    regslice_both_stream_in_3_V_strb_V_U_apdone_blk;
wire   [3:0] stream_in_3_TSTRB_int_regslice;
wire    regslice_both_stream_in_3_V_strb_V_U_vld_out;
wire    regslice_both_stream_in_3_V_strb_V_U_ack_in;
wire    regslice_both_stream_in_3_V_user_V_U_apdone_blk;
wire   [1:0] stream_in_3_TUSER_int_regslice;
wire    regslice_both_stream_in_3_V_user_V_U_vld_out;
wire    regslice_both_stream_in_3_V_user_V_U_ack_in;
wire    regslice_both_stream_in_3_V_last_V_U_apdone_blk;
wire   [0:0] stream_in_3_TLAST_int_regslice;
wire    regslice_both_stream_in_3_V_last_V_U_vld_out;
wire    regslice_both_stream_in_3_V_last_V_U_ack_in;
wire    regslice_both_stream_in_3_V_id_V_U_apdone_blk;
wire   [4:0] stream_in_3_TID_int_regslice;
wire    regslice_both_stream_in_3_V_id_V_U_vld_out;
wire    regslice_both_stream_in_3_V_id_V_U_ack_in;
wire    regslice_both_stream_in_3_V_dest_V_U_apdone_blk;
wire   [5:0] stream_in_3_TDEST_int_regslice;
wire    regslice_both_stream_in_3_V_dest_V_U_vld_out;
wire    regslice_both_stream_in_3_V_dest_V_U_ack_in;
wire    regslice_both_stream_in_4_V_data_V_U_apdone_blk;
wire   [31:0] stream_in_4_TDATA_int_regslice;
wire    stream_in_4_TVALID_int_regslice;
reg    stream_in_4_TREADY_int_regslice;
wire    regslice_both_stream_in_4_V_data_V_U_ack_in;
wire    regslice_both_stream_in_4_V_keep_V_U_apdone_blk;
wire   [3:0] stream_in_4_TKEEP_int_regslice;
wire    regslice_both_stream_in_4_V_keep_V_U_vld_out;
wire    regslice_both_stream_in_4_V_keep_V_U_ack_in;
wire    regslice_both_stream_in_4_V_strb_V_U_apdone_blk;
wire   [3:0] stream_in_4_TSTRB_int_regslice;
wire    regslice_both_stream_in_4_V_strb_V_U_vld_out;
wire    regslice_both_stream_in_4_V_strb_V_U_ack_in;
wire    regslice_both_stream_in_4_V_user_V_U_apdone_blk;
wire   [1:0] stream_in_4_TUSER_int_regslice;
wire    regslice_both_stream_in_4_V_user_V_U_vld_out;
wire    regslice_both_stream_in_4_V_user_V_U_ack_in;
wire    regslice_both_stream_in_4_V_last_V_U_apdone_blk;
wire   [0:0] stream_in_4_TLAST_int_regslice;
wire    regslice_both_stream_in_4_V_last_V_U_vld_out;
wire    regslice_both_stream_in_4_V_last_V_U_ack_in;
wire    regslice_both_stream_in_4_V_id_V_U_apdone_blk;
wire   [4:0] stream_in_4_TID_int_regslice;
wire    regslice_both_stream_in_4_V_id_V_U_vld_out;
wire    regslice_both_stream_in_4_V_id_V_U_ack_in;
wire    regslice_both_stream_in_4_V_dest_V_U_apdone_blk;
wire   [5:0] stream_in_4_TDEST_int_regslice;
wire    regslice_both_stream_in_4_V_dest_V_U_vld_out;
wire    regslice_both_stream_in_4_V_dest_V_U_ack_in;
wire    regslice_both_stream_in_5_V_data_V_U_apdone_blk;
wire   [31:0] stream_in_5_TDATA_int_regslice;
wire    stream_in_5_TVALID_int_regslice;
reg    stream_in_5_TREADY_int_regslice;
wire    regslice_both_stream_in_5_V_data_V_U_ack_in;
wire    regslice_both_stream_in_5_V_keep_V_U_apdone_blk;
wire   [3:0] stream_in_5_TKEEP_int_regslice;
wire    regslice_both_stream_in_5_V_keep_V_U_vld_out;
wire    regslice_both_stream_in_5_V_keep_V_U_ack_in;
wire    regslice_both_stream_in_5_V_strb_V_U_apdone_blk;
wire   [3:0] stream_in_5_TSTRB_int_regslice;
wire    regslice_both_stream_in_5_V_strb_V_U_vld_out;
wire    regslice_both_stream_in_5_V_strb_V_U_ack_in;
wire    regslice_both_stream_in_5_V_user_V_U_apdone_blk;
wire   [1:0] stream_in_5_TUSER_int_regslice;
wire    regslice_both_stream_in_5_V_user_V_U_vld_out;
wire    regslice_both_stream_in_5_V_user_V_U_ack_in;
wire    regslice_both_stream_in_5_V_last_V_U_apdone_blk;
wire   [0:0] stream_in_5_TLAST_int_regslice;
wire    regslice_both_stream_in_5_V_last_V_U_vld_out;
wire    regslice_both_stream_in_5_V_last_V_U_ack_in;
wire    regslice_both_stream_in_5_V_id_V_U_apdone_blk;
wire   [4:0] stream_in_5_TID_int_regslice;
wire    regslice_both_stream_in_5_V_id_V_U_vld_out;
wire    regslice_both_stream_in_5_V_id_V_U_ack_in;
wire    regslice_both_stream_in_5_V_dest_V_U_apdone_blk;
wire   [5:0] stream_in_5_TDEST_int_regslice;
wire    regslice_both_stream_in_5_V_dest_V_U_vld_out;
wire    regslice_both_stream_in_5_V_dest_V_U_ack_in;
wire    regslice_both_stream_in_6_V_data_V_U_apdone_blk;
wire   [31:0] stream_in_6_TDATA_int_regslice;
wire    stream_in_6_TVALID_int_regslice;
reg    stream_in_6_TREADY_int_regslice;
wire    regslice_both_stream_in_6_V_data_V_U_ack_in;
wire    regslice_both_stream_in_6_V_keep_V_U_apdone_blk;
wire   [3:0] stream_in_6_TKEEP_int_regslice;
wire    regslice_both_stream_in_6_V_keep_V_U_vld_out;
wire    regslice_both_stream_in_6_V_keep_V_U_ack_in;
wire    regslice_both_stream_in_6_V_strb_V_U_apdone_blk;
wire   [3:0] stream_in_6_TSTRB_int_regslice;
wire    regslice_both_stream_in_6_V_strb_V_U_vld_out;
wire    regslice_both_stream_in_6_V_strb_V_U_ack_in;
wire    regslice_both_stream_in_6_V_user_V_U_apdone_blk;
wire   [1:0] stream_in_6_TUSER_int_regslice;
wire    regslice_both_stream_in_6_V_user_V_U_vld_out;
wire    regslice_both_stream_in_6_V_user_V_U_ack_in;
wire    regslice_both_stream_in_6_V_last_V_U_apdone_blk;
wire   [0:0] stream_in_6_TLAST_int_regslice;
wire    regslice_both_stream_in_6_V_last_V_U_vld_out;
wire    regslice_both_stream_in_6_V_last_V_U_ack_in;
wire    regslice_both_stream_in_6_V_id_V_U_apdone_blk;
wire   [4:0] stream_in_6_TID_int_regslice;
wire    regslice_both_stream_in_6_V_id_V_U_vld_out;
wire    regslice_both_stream_in_6_V_id_V_U_ack_in;
wire    regslice_both_stream_in_6_V_dest_V_U_apdone_blk;
wire   [5:0] stream_in_6_TDEST_int_regslice;
wire    regslice_both_stream_in_6_V_dest_V_U_vld_out;
wire    regslice_both_stream_in_6_V_dest_V_U_ack_in;
wire    regslice_both_stream_in_7_V_data_V_U_apdone_blk;
wire   [31:0] stream_in_7_TDATA_int_regslice;
wire    stream_in_7_TVALID_int_regslice;
reg    stream_in_7_TREADY_int_regslice;
wire    regslice_both_stream_in_7_V_data_V_U_ack_in;
wire    regslice_both_stream_in_7_V_keep_V_U_apdone_blk;
wire   [3:0] stream_in_7_TKEEP_int_regslice;
wire    regslice_both_stream_in_7_V_keep_V_U_vld_out;
wire    regslice_both_stream_in_7_V_keep_V_U_ack_in;
wire    regslice_both_stream_in_7_V_strb_V_U_apdone_blk;
wire   [3:0] stream_in_7_TSTRB_int_regslice;
wire    regslice_both_stream_in_7_V_strb_V_U_vld_out;
wire    regslice_both_stream_in_7_V_strb_V_U_ack_in;
wire    regslice_both_stream_in_7_V_user_V_U_apdone_blk;
wire   [1:0] stream_in_7_TUSER_int_regslice;
wire    regslice_both_stream_in_7_V_user_V_U_vld_out;
wire    regslice_both_stream_in_7_V_user_V_U_ack_in;
wire    regslice_both_stream_in_7_V_last_V_U_apdone_blk;
wire   [0:0] stream_in_7_TLAST_int_regslice;
wire    regslice_both_stream_in_7_V_last_V_U_vld_out;
wire    regslice_both_stream_in_7_V_last_V_U_ack_in;
wire    regslice_both_stream_in_7_V_id_V_U_apdone_blk;
wire   [4:0] stream_in_7_TID_int_regslice;
wire    regslice_both_stream_in_7_V_id_V_U_vld_out;
wire    regslice_both_stream_in_7_V_id_V_U_ack_in;
wire    regslice_both_stream_in_7_V_dest_V_U_apdone_blk;
wire   [5:0] stream_in_7_TDEST_int_regslice;
wire    regslice_both_stream_in_7_V_dest_V_U_vld_out;
wire    regslice_both_stream_in_7_V_dest_V_U_ack_in;
reg   [31:0] mix_out_TDATA_int_regslice;
reg    mix_out_TVALID_int_regslice;
wire    mix_out_TREADY_int_regslice;
wire    regslice_both_mix_out_V_data_V_U_vld_out;
wire    regslice_both_mix_out_V_keep_V_U_apdone_blk;
reg   [3:0] mix_out_TKEEP_int_regslice;
wire    regslice_both_mix_out_V_keep_V_U_ack_in_dummy;
wire    regslice_both_mix_out_V_keep_V_U_vld_out;
wire    regslice_both_mix_out_V_strb_V_U_apdone_blk;
reg   [3:0] mix_out_TSTRB_int_regslice;
wire    regslice_both_mix_out_V_strb_V_U_ack_in_dummy;
wire    regslice_both_mix_out_V_strb_V_U_vld_out;
wire    regslice_both_mix_out_V_user_V_U_apdone_blk;
reg   [1:0] mix_out_TUSER_int_regslice;
wire    regslice_both_mix_out_V_user_V_U_ack_in_dummy;
wire    regslice_both_mix_out_V_user_V_U_vld_out;
wire    regslice_both_mix_out_V_last_V_U_apdone_blk;
reg   [0:0] mix_out_TLAST_int_regslice;
wire    regslice_both_mix_out_V_last_V_U_ack_in_dummy;
wire    regslice_both_mix_out_V_last_V_U_vld_out;
wire    regslice_both_mix_out_V_id_V_U_apdone_blk;
reg   [4:0] mix_out_TID_int_regslice;
wire    regslice_both_mix_out_V_id_V_U_ack_in_dummy;
wire    regslice_both_mix_out_V_id_V_U_vld_out;
wire    regslice_both_mix_out_V_dest_V_U_apdone_blk;
reg   [5:0] mix_out_TDEST_int_regslice;
wire    regslice_both_mix_out_V_dest_V_U_ack_in_dummy;
wire    regslice_both_mix_out_V_dest_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_ap_start_reg = 1'b0;
end

mixer_mixer_Pipeline_VITIS_LOOP_30_1 grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_ap_start),
    .ap_done(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_ap_done),
    .ap_idle(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_ap_idle),
    .ap_ready(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_ap_ready),
    .stream_in_0_TVALID(stream_in_0_TVALID_int_regslice),
    .stream_in_1_TVALID(stream_in_1_TVALID_int_regslice),
    .stream_in_2_TVALID(stream_in_2_TVALID_int_regslice),
    .stream_in_3_TVALID(stream_in_3_TVALID_int_regslice),
    .stream_in_4_TVALID(stream_in_4_TVALID_int_regslice),
    .stream_in_5_TVALID(stream_in_5_TVALID_int_regslice),
    .stream_in_6_TVALID(stream_in_6_TVALID_int_regslice),
    .stream_in_7_TVALID(stream_in_7_TVALID_int_regslice),
    .mix_out_TREADY(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TREADY),
    .active_14(select_ln61_reg_617),
    .mix_out_TDATA(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TDATA),
    .mix_out_TVALID(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TVALID),
    .mix_out_TKEEP(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TKEEP),
    .mix_out_TSTRB(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TSTRB),
    .mix_out_TUSER(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TUSER),
    .mix_out_TLAST(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TLAST),
    .mix_out_TID(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TID),
    .mix_out_TDEST(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TDEST),
    .stream_in_0_TDATA(stream_in_0_TDATA_int_regslice),
    .stream_in_0_TREADY(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_0_TREADY),
    .stream_in_0_TKEEP(stream_in_0_TKEEP_int_regslice),
    .stream_in_0_TSTRB(stream_in_0_TSTRB_int_regslice),
    .stream_in_0_TUSER(stream_in_0_TUSER_int_regslice),
    .stream_in_0_TLAST(stream_in_0_TLAST_int_regslice),
    .stream_in_0_TID(stream_in_0_TID_int_regslice),
    .stream_in_0_TDEST(stream_in_0_TDEST_int_regslice),
    .stream_in_1_TDATA(stream_in_1_TDATA_int_regslice),
    .stream_in_1_TREADY(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_1_TREADY),
    .stream_in_1_TKEEP(stream_in_1_TKEEP_int_regslice),
    .stream_in_1_TSTRB(stream_in_1_TSTRB_int_regslice),
    .stream_in_1_TUSER(stream_in_1_TUSER_int_regslice),
    .stream_in_1_TLAST(stream_in_1_TLAST_int_regslice),
    .stream_in_1_TID(stream_in_1_TID_int_regslice),
    .stream_in_1_TDEST(stream_in_1_TDEST_int_regslice),
    .stream_in_2_TDATA(stream_in_2_TDATA_int_regslice),
    .stream_in_2_TREADY(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_2_TREADY),
    .stream_in_2_TKEEP(stream_in_2_TKEEP_int_regslice),
    .stream_in_2_TSTRB(stream_in_2_TSTRB_int_regslice),
    .stream_in_2_TUSER(stream_in_2_TUSER_int_regslice),
    .stream_in_2_TLAST(stream_in_2_TLAST_int_regslice),
    .stream_in_2_TID(stream_in_2_TID_int_regslice),
    .stream_in_2_TDEST(stream_in_2_TDEST_int_regslice),
    .stream_in_3_TDATA(stream_in_3_TDATA_int_regslice),
    .stream_in_3_TREADY(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_3_TREADY),
    .stream_in_3_TKEEP(stream_in_3_TKEEP_int_regslice),
    .stream_in_3_TSTRB(stream_in_3_TSTRB_int_regslice),
    .stream_in_3_TUSER(stream_in_3_TUSER_int_regslice),
    .stream_in_3_TLAST(stream_in_3_TLAST_int_regslice),
    .stream_in_3_TID(stream_in_3_TID_int_regslice),
    .stream_in_3_TDEST(stream_in_3_TDEST_int_regslice),
    .stream_in_4_TDATA(stream_in_4_TDATA_int_regslice),
    .stream_in_4_TREADY(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_4_TREADY),
    .stream_in_4_TKEEP(stream_in_4_TKEEP_int_regslice),
    .stream_in_4_TSTRB(stream_in_4_TSTRB_int_regslice),
    .stream_in_4_TUSER(stream_in_4_TUSER_int_regslice),
    .stream_in_4_TLAST(stream_in_4_TLAST_int_regslice),
    .stream_in_4_TID(stream_in_4_TID_int_regslice),
    .stream_in_4_TDEST(stream_in_4_TDEST_int_regslice),
    .stream_in_5_TDATA(stream_in_5_TDATA_int_regslice),
    .stream_in_5_TREADY(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_5_TREADY),
    .stream_in_5_TKEEP(stream_in_5_TKEEP_int_regslice),
    .stream_in_5_TSTRB(stream_in_5_TSTRB_int_regslice),
    .stream_in_5_TUSER(stream_in_5_TUSER_int_regslice),
    .stream_in_5_TLAST(stream_in_5_TLAST_int_regslice),
    .stream_in_5_TID(stream_in_5_TID_int_regslice),
    .stream_in_5_TDEST(stream_in_5_TDEST_int_regslice),
    .stream_in_6_TDATA(stream_in_6_TDATA_int_regslice),
    .stream_in_6_TREADY(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_6_TREADY),
    .stream_in_6_TKEEP(stream_in_6_TKEEP_int_regslice),
    .stream_in_6_TSTRB(stream_in_6_TSTRB_int_regslice),
    .stream_in_6_TUSER(stream_in_6_TUSER_int_regslice),
    .stream_in_6_TLAST(stream_in_6_TLAST_int_regslice),
    .stream_in_6_TID(stream_in_6_TID_int_regslice),
    .stream_in_6_TDEST(stream_in_6_TDEST_int_regslice),
    .stream_in_7_TDATA(stream_in_7_TDATA_int_regslice),
    .stream_in_7_TREADY(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_7_TREADY),
    .stream_in_7_TKEEP(stream_in_7_TKEEP_int_regslice),
    .stream_in_7_TSTRB(stream_in_7_TSTRB_int_regslice),
    .stream_in_7_TUSER(stream_in_7_TUSER_int_regslice),
    .stream_in_7_TLAST(stream_in_7_TLAST_int_regslice),
    .stream_in_7_TID(stream_in_7_TID_int_regslice),
    .stream_in_7_TDEST(stream_in_7_TDEST_int_regslice),
    .empty_16(trunc_ln54_reg_577),
    .empty_17(tmp_reg_582),
    .empty_18(tmp_8_reg_587),
    .empty_19(tmp_9_reg_592),
    .empty_20(tmp_10_reg_597),
    .empty_21(tmp_11_reg_602),
    .empty_22(tmp_12_reg_607),
    .empty(tmp_13_reg_612),
    .out_pkt_data_out(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_out_pkt_data_out),
    .out_pkt_data_out_ap_vld(grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_out_pkt_data_out_ap_vld)
);

mixer_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

mixer_regslice_both #(
    .DataWidth( 32 ))
regslice_both_stream_in_0_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_0_TDATA),
    .vld_in(stream_in_0_TVALID),
    .ack_in(regslice_both_stream_in_0_V_data_V_U_ack_in),
    .data_out(stream_in_0_TDATA_int_regslice),
    .vld_out(stream_in_0_TVALID_int_regslice),
    .ack_out(stream_in_0_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_0_V_data_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_in_0_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_0_TKEEP),
    .vld_in(stream_in_0_TVALID),
    .ack_in(regslice_both_stream_in_0_V_keep_V_U_ack_in),
    .data_out(stream_in_0_TKEEP_int_regslice),
    .vld_out(regslice_both_stream_in_0_V_keep_V_U_vld_out),
    .ack_out(stream_in_0_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_0_V_keep_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_in_0_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_0_TSTRB),
    .vld_in(stream_in_0_TVALID),
    .ack_in(regslice_both_stream_in_0_V_strb_V_U_ack_in),
    .data_out(stream_in_0_TSTRB_int_regslice),
    .vld_out(regslice_both_stream_in_0_V_strb_V_U_vld_out),
    .ack_out(stream_in_0_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_0_V_strb_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 2 ))
regslice_both_stream_in_0_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_0_TUSER),
    .vld_in(stream_in_0_TVALID),
    .ack_in(regslice_both_stream_in_0_V_user_V_U_ack_in),
    .data_out(stream_in_0_TUSER_int_regslice),
    .vld_out(regslice_both_stream_in_0_V_user_V_U_vld_out),
    .ack_out(stream_in_0_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_0_V_user_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_0_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_0_TLAST),
    .vld_in(stream_in_0_TVALID),
    .ack_in(regslice_both_stream_in_0_V_last_V_U_ack_in),
    .data_out(stream_in_0_TLAST_int_regslice),
    .vld_out(regslice_both_stream_in_0_V_last_V_U_vld_out),
    .ack_out(stream_in_0_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_0_V_last_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 5 ))
regslice_both_stream_in_0_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_0_TID),
    .vld_in(stream_in_0_TVALID),
    .ack_in(regslice_both_stream_in_0_V_id_V_U_ack_in),
    .data_out(stream_in_0_TID_int_regslice),
    .vld_out(regslice_both_stream_in_0_V_id_V_U_vld_out),
    .ack_out(stream_in_0_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_0_V_id_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 6 ))
regslice_both_stream_in_0_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_0_TDEST),
    .vld_in(stream_in_0_TVALID),
    .ack_in(regslice_both_stream_in_0_V_dest_V_U_ack_in),
    .data_out(stream_in_0_TDEST_int_regslice),
    .vld_out(regslice_both_stream_in_0_V_dest_V_U_vld_out),
    .ack_out(stream_in_0_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_0_V_dest_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 32 ))
regslice_both_stream_in_1_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_1_TDATA),
    .vld_in(stream_in_1_TVALID),
    .ack_in(regslice_both_stream_in_1_V_data_V_U_ack_in),
    .data_out(stream_in_1_TDATA_int_regslice),
    .vld_out(stream_in_1_TVALID_int_regslice),
    .ack_out(stream_in_1_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_1_V_data_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_in_1_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_1_TKEEP),
    .vld_in(stream_in_1_TVALID),
    .ack_in(regslice_both_stream_in_1_V_keep_V_U_ack_in),
    .data_out(stream_in_1_TKEEP_int_regslice),
    .vld_out(regslice_both_stream_in_1_V_keep_V_U_vld_out),
    .ack_out(stream_in_1_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_1_V_keep_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_in_1_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_1_TSTRB),
    .vld_in(stream_in_1_TVALID),
    .ack_in(regslice_both_stream_in_1_V_strb_V_U_ack_in),
    .data_out(stream_in_1_TSTRB_int_regslice),
    .vld_out(regslice_both_stream_in_1_V_strb_V_U_vld_out),
    .ack_out(stream_in_1_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_1_V_strb_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 2 ))
regslice_both_stream_in_1_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_1_TUSER),
    .vld_in(stream_in_1_TVALID),
    .ack_in(regslice_both_stream_in_1_V_user_V_U_ack_in),
    .data_out(stream_in_1_TUSER_int_regslice),
    .vld_out(regslice_both_stream_in_1_V_user_V_U_vld_out),
    .ack_out(stream_in_1_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_1_V_user_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_1_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_1_TLAST),
    .vld_in(stream_in_1_TVALID),
    .ack_in(regslice_both_stream_in_1_V_last_V_U_ack_in),
    .data_out(stream_in_1_TLAST_int_regslice),
    .vld_out(regslice_both_stream_in_1_V_last_V_U_vld_out),
    .ack_out(stream_in_1_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_1_V_last_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 5 ))
regslice_both_stream_in_1_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_1_TID),
    .vld_in(stream_in_1_TVALID),
    .ack_in(regslice_both_stream_in_1_V_id_V_U_ack_in),
    .data_out(stream_in_1_TID_int_regslice),
    .vld_out(regslice_both_stream_in_1_V_id_V_U_vld_out),
    .ack_out(stream_in_1_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_1_V_id_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 6 ))
regslice_both_stream_in_1_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_1_TDEST),
    .vld_in(stream_in_1_TVALID),
    .ack_in(regslice_both_stream_in_1_V_dest_V_U_ack_in),
    .data_out(stream_in_1_TDEST_int_regslice),
    .vld_out(regslice_both_stream_in_1_V_dest_V_U_vld_out),
    .ack_out(stream_in_1_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_1_V_dest_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 32 ))
regslice_both_stream_in_2_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_2_TDATA),
    .vld_in(stream_in_2_TVALID),
    .ack_in(regslice_both_stream_in_2_V_data_V_U_ack_in),
    .data_out(stream_in_2_TDATA_int_regslice),
    .vld_out(stream_in_2_TVALID_int_regslice),
    .ack_out(stream_in_2_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_2_V_data_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_in_2_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_2_TKEEP),
    .vld_in(stream_in_2_TVALID),
    .ack_in(regslice_both_stream_in_2_V_keep_V_U_ack_in),
    .data_out(stream_in_2_TKEEP_int_regslice),
    .vld_out(regslice_both_stream_in_2_V_keep_V_U_vld_out),
    .ack_out(stream_in_2_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_2_V_keep_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_in_2_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_2_TSTRB),
    .vld_in(stream_in_2_TVALID),
    .ack_in(regslice_both_stream_in_2_V_strb_V_U_ack_in),
    .data_out(stream_in_2_TSTRB_int_regslice),
    .vld_out(regslice_both_stream_in_2_V_strb_V_U_vld_out),
    .ack_out(stream_in_2_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_2_V_strb_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 2 ))
regslice_both_stream_in_2_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_2_TUSER),
    .vld_in(stream_in_2_TVALID),
    .ack_in(regslice_both_stream_in_2_V_user_V_U_ack_in),
    .data_out(stream_in_2_TUSER_int_regslice),
    .vld_out(regslice_both_stream_in_2_V_user_V_U_vld_out),
    .ack_out(stream_in_2_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_2_V_user_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_2_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_2_TLAST),
    .vld_in(stream_in_2_TVALID),
    .ack_in(regslice_both_stream_in_2_V_last_V_U_ack_in),
    .data_out(stream_in_2_TLAST_int_regslice),
    .vld_out(regslice_both_stream_in_2_V_last_V_U_vld_out),
    .ack_out(stream_in_2_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_2_V_last_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 5 ))
regslice_both_stream_in_2_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_2_TID),
    .vld_in(stream_in_2_TVALID),
    .ack_in(regslice_both_stream_in_2_V_id_V_U_ack_in),
    .data_out(stream_in_2_TID_int_regslice),
    .vld_out(regslice_both_stream_in_2_V_id_V_U_vld_out),
    .ack_out(stream_in_2_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_2_V_id_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 6 ))
regslice_both_stream_in_2_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_2_TDEST),
    .vld_in(stream_in_2_TVALID),
    .ack_in(regslice_both_stream_in_2_V_dest_V_U_ack_in),
    .data_out(stream_in_2_TDEST_int_regslice),
    .vld_out(regslice_both_stream_in_2_V_dest_V_U_vld_out),
    .ack_out(stream_in_2_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_2_V_dest_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 32 ))
regslice_both_stream_in_3_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_3_TDATA),
    .vld_in(stream_in_3_TVALID),
    .ack_in(regslice_both_stream_in_3_V_data_V_U_ack_in),
    .data_out(stream_in_3_TDATA_int_regslice),
    .vld_out(stream_in_3_TVALID_int_regslice),
    .ack_out(stream_in_3_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_3_V_data_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_in_3_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_3_TKEEP),
    .vld_in(stream_in_3_TVALID),
    .ack_in(regslice_both_stream_in_3_V_keep_V_U_ack_in),
    .data_out(stream_in_3_TKEEP_int_regslice),
    .vld_out(regslice_both_stream_in_3_V_keep_V_U_vld_out),
    .ack_out(stream_in_3_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_3_V_keep_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_in_3_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_3_TSTRB),
    .vld_in(stream_in_3_TVALID),
    .ack_in(regslice_both_stream_in_3_V_strb_V_U_ack_in),
    .data_out(stream_in_3_TSTRB_int_regslice),
    .vld_out(regslice_both_stream_in_3_V_strb_V_U_vld_out),
    .ack_out(stream_in_3_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_3_V_strb_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 2 ))
regslice_both_stream_in_3_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_3_TUSER),
    .vld_in(stream_in_3_TVALID),
    .ack_in(regslice_both_stream_in_3_V_user_V_U_ack_in),
    .data_out(stream_in_3_TUSER_int_regslice),
    .vld_out(regslice_both_stream_in_3_V_user_V_U_vld_out),
    .ack_out(stream_in_3_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_3_V_user_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_3_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_3_TLAST),
    .vld_in(stream_in_3_TVALID),
    .ack_in(regslice_both_stream_in_3_V_last_V_U_ack_in),
    .data_out(stream_in_3_TLAST_int_regslice),
    .vld_out(regslice_both_stream_in_3_V_last_V_U_vld_out),
    .ack_out(stream_in_3_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_3_V_last_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 5 ))
regslice_both_stream_in_3_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_3_TID),
    .vld_in(stream_in_3_TVALID),
    .ack_in(regslice_both_stream_in_3_V_id_V_U_ack_in),
    .data_out(stream_in_3_TID_int_regslice),
    .vld_out(regslice_both_stream_in_3_V_id_V_U_vld_out),
    .ack_out(stream_in_3_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_3_V_id_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 6 ))
regslice_both_stream_in_3_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_3_TDEST),
    .vld_in(stream_in_3_TVALID),
    .ack_in(regslice_both_stream_in_3_V_dest_V_U_ack_in),
    .data_out(stream_in_3_TDEST_int_regslice),
    .vld_out(regslice_both_stream_in_3_V_dest_V_U_vld_out),
    .ack_out(stream_in_3_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_3_V_dest_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 32 ))
regslice_both_stream_in_4_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_4_TDATA),
    .vld_in(stream_in_4_TVALID),
    .ack_in(regslice_both_stream_in_4_V_data_V_U_ack_in),
    .data_out(stream_in_4_TDATA_int_regslice),
    .vld_out(stream_in_4_TVALID_int_regslice),
    .ack_out(stream_in_4_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_4_V_data_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_in_4_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_4_TKEEP),
    .vld_in(stream_in_4_TVALID),
    .ack_in(regslice_both_stream_in_4_V_keep_V_U_ack_in),
    .data_out(stream_in_4_TKEEP_int_regslice),
    .vld_out(regslice_both_stream_in_4_V_keep_V_U_vld_out),
    .ack_out(stream_in_4_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_4_V_keep_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_in_4_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_4_TSTRB),
    .vld_in(stream_in_4_TVALID),
    .ack_in(regslice_both_stream_in_4_V_strb_V_U_ack_in),
    .data_out(stream_in_4_TSTRB_int_regslice),
    .vld_out(regslice_both_stream_in_4_V_strb_V_U_vld_out),
    .ack_out(stream_in_4_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_4_V_strb_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 2 ))
regslice_both_stream_in_4_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_4_TUSER),
    .vld_in(stream_in_4_TVALID),
    .ack_in(regslice_both_stream_in_4_V_user_V_U_ack_in),
    .data_out(stream_in_4_TUSER_int_regslice),
    .vld_out(regslice_both_stream_in_4_V_user_V_U_vld_out),
    .ack_out(stream_in_4_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_4_V_user_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_4_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_4_TLAST),
    .vld_in(stream_in_4_TVALID),
    .ack_in(regslice_both_stream_in_4_V_last_V_U_ack_in),
    .data_out(stream_in_4_TLAST_int_regslice),
    .vld_out(regslice_both_stream_in_4_V_last_V_U_vld_out),
    .ack_out(stream_in_4_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_4_V_last_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 5 ))
regslice_both_stream_in_4_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_4_TID),
    .vld_in(stream_in_4_TVALID),
    .ack_in(regslice_both_stream_in_4_V_id_V_U_ack_in),
    .data_out(stream_in_4_TID_int_regslice),
    .vld_out(regslice_both_stream_in_4_V_id_V_U_vld_out),
    .ack_out(stream_in_4_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_4_V_id_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 6 ))
regslice_both_stream_in_4_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_4_TDEST),
    .vld_in(stream_in_4_TVALID),
    .ack_in(regslice_both_stream_in_4_V_dest_V_U_ack_in),
    .data_out(stream_in_4_TDEST_int_regslice),
    .vld_out(regslice_both_stream_in_4_V_dest_V_U_vld_out),
    .ack_out(stream_in_4_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_4_V_dest_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 32 ))
regslice_both_stream_in_5_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_5_TDATA),
    .vld_in(stream_in_5_TVALID),
    .ack_in(regslice_both_stream_in_5_V_data_V_U_ack_in),
    .data_out(stream_in_5_TDATA_int_regslice),
    .vld_out(stream_in_5_TVALID_int_regslice),
    .ack_out(stream_in_5_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_5_V_data_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_in_5_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_5_TKEEP),
    .vld_in(stream_in_5_TVALID),
    .ack_in(regslice_both_stream_in_5_V_keep_V_U_ack_in),
    .data_out(stream_in_5_TKEEP_int_regslice),
    .vld_out(regslice_both_stream_in_5_V_keep_V_U_vld_out),
    .ack_out(stream_in_5_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_5_V_keep_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_in_5_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_5_TSTRB),
    .vld_in(stream_in_5_TVALID),
    .ack_in(regslice_both_stream_in_5_V_strb_V_U_ack_in),
    .data_out(stream_in_5_TSTRB_int_regslice),
    .vld_out(regslice_both_stream_in_5_V_strb_V_U_vld_out),
    .ack_out(stream_in_5_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_5_V_strb_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 2 ))
regslice_both_stream_in_5_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_5_TUSER),
    .vld_in(stream_in_5_TVALID),
    .ack_in(regslice_both_stream_in_5_V_user_V_U_ack_in),
    .data_out(stream_in_5_TUSER_int_regslice),
    .vld_out(regslice_both_stream_in_5_V_user_V_U_vld_out),
    .ack_out(stream_in_5_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_5_V_user_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_5_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_5_TLAST),
    .vld_in(stream_in_5_TVALID),
    .ack_in(regslice_both_stream_in_5_V_last_V_U_ack_in),
    .data_out(stream_in_5_TLAST_int_regslice),
    .vld_out(regslice_both_stream_in_5_V_last_V_U_vld_out),
    .ack_out(stream_in_5_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_5_V_last_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 5 ))
regslice_both_stream_in_5_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_5_TID),
    .vld_in(stream_in_5_TVALID),
    .ack_in(regslice_both_stream_in_5_V_id_V_U_ack_in),
    .data_out(stream_in_5_TID_int_regslice),
    .vld_out(regslice_both_stream_in_5_V_id_V_U_vld_out),
    .ack_out(stream_in_5_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_5_V_id_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 6 ))
regslice_both_stream_in_5_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_5_TDEST),
    .vld_in(stream_in_5_TVALID),
    .ack_in(regslice_both_stream_in_5_V_dest_V_U_ack_in),
    .data_out(stream_in_5_TDEST_int_regslice),
    .vld_out(regslice_both_stream_in_5_V_dest_V_U_vld_out),
    .ack_out(stream_in_5_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_5_V_dest_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 32 ))
regslice_both_stream_in_6_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_6_TDATA),
    .vld_in(stream_in_6_TVALID),
    .ack_in(regslice_both_stream_in_6_V_data_V_U_ack_in),
    .data_out(stream_in_6_TDATA_int_regslice),
    .vld_out(stream_in_6_TVALID_int_regslice),
    .ack_out(stream_in_6_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_6_V_data_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_in_6_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_6_TKEEP),
    .vld_in(stream_in_6_TVALID),
    .ack_in(regslice_both_stream_in_6_V_keep_V_U_ack_in),
    .data_out(stream_in_6_TKEEP_int_regslice),
    .vld_out(regslice_both_stream_in_6_V_keep_V_U_vld_out),
    .ack_out(stream_in_6_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_6_V_keep_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_in_6_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_6_TSTRB),
    .vld_in(stream_in_6_TVALID),
    .ack_in(regslice_both_stream_in_6_V_strb_V_U_ack_in),
    .data_out(stream_in_6_TSTRB_int_regslice),
    .vld_out(regslice_both_stream_in_6_V_strb_V_U_vld_out),
    .ack_out(stream_in_6_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_6_V_strb_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 2 ))
regslice_both_stream_in_6_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_6_TUSER),
    .vld_in(stream_in_6_TVALID),
    .ack_in(regslice_both_stream_in_6_V_user_V_U_ack_in),
    .data_out(stream_in_6_TUSER_int_regslice),
    .vld_out(regslice_both_stream_in_6_V_user_V_U_vld_out),
    .ack_out(stream_in_6_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_6_V_user_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_6_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_6_TLAST),
    .vld_in(stream_in_6_TVALID),
    .ack_in(regslice_both_stream_in_6_V_last_V_U_ack_in),
    .data_out(stream_in_6_TLAST_int_regslice),
    .vld_out(regslice_both_stream_in_6_V_last_V_U_vld_out),
    .ack_out(stream_in_6_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_6_V_last_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 5 ))
regslice_both_stream_in_6_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_6_TID),
    .vld_in(stream_in_6_TVALID),
    .ack_in(regslice_both_stream_in_6_V_id_V_U_ack_in),
    .data_out(stream_in_6_TID_int_regslice),
    .vld_out(regslice_both_stream_in_6_V_id_V_U_vld_out),
    .ack_out(stream_in_6_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_6_V_id_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 6 ))
regslice_both_stream_in_6_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_6_TDEST),
    .vld_in(stream_in_6_TVALID),
    .ack_in(regslice_both_stream_in_6_V_dest_V_U_ack_in),
    .data_out(stream_in_6_TDEST_int_regslice),
    .vld_out(regslice_both_stream_in_6_V_dest_V_U_vld_out),
    .ack_out(stream_in_6_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_6_V_dest_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 32 ))
regslice_both_stream_in_7_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_7_TDATA),
    .vld_in(stream_in_7_TVALID),
    .ack_in(regslice_both_stream_in_7_V_data_V_U_ack_in),
    .data_out(stream_in_7_TDATA_int_regslice),
    .vld_out(stream_in_7_TVALID_int_regslice),
    .ack_out(stream_in_7_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_7_V_data_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_in_7_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_7_TKEEP),
    .vld_in(stream_in_7_TVALID),
    .ack_in(regslice_both_stream_in_7_V_keep_V_U_ack_in),
    .data_out(stream_in_7_TKEEP_int_regslice),
    .vld_out(regslice_both_stream_in_7_V_keep_V_U_vld_out),
    .ack_out(stream_in_7_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_7_V_keep_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_in_7_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_7_TSTRB),
    .vld_in(stream_in_7_TVALID),
    .ack_in(regslice_both_stream_in_7_V_strb_V_U_ack_in),
    .data_out(stream_in_7_TSTRB_int_regslice),
    .vld_out(regslice_both_stream_in_7_V_strb_V_U_vld_out),
    .ack_out(stream_in_7_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_7_V_strb_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 2 ))
regslice_both_stream_in_7_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_7_TUSER),
    .vld_in(stream_in_7_TVALID),
    .ack_in(regslice_both_stream_in_7_V_user_V_U_ack_in),
    .data_out(stream_in_7_TUSER_int_regslice),
    .vld_out(regslice_both_stream_in_7_V_user_V_U_vld_out),
    .ack_out(stream_in_7_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_7_V_user_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_7_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_7_TLAST),
    .vld_in(stream_in_7_TVALID),
    .ack_in(regslice_both_stream_in_7_V_last_V_U_ack_in),
    .data_out(stream_in_7_TLAST_int_regslice),
    .vld_out(regslice_both_stream_in_7_V_last_V_U_vld_out),
    .ack_out(stream_in_7_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_7_V_last_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 5 ))
regslice_both_stream_in_7_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_7_TID),
    .vld_in(stream_in_7_TVALID),
    .ack_in(regslice_both_stream_in_7_V_id_V_U_ack_in),
    .data_out(stream_in_7_TID_int_regslice),
    .vld_out(regslice_both_stream_in_7_V_id_V_U_vld_out),
    .ack_out(stream_in_7_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_7_V_id_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 6 ))
regslice_both_stream_in_7_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_7_TDEST),
    .vld_in(stream_in_7_TVALID),
    .ack_in(regslice_both_stream_in_7_V_dest_V_U_ack_in),
    .data_out(stream_in_7_TDEST_int_regslice),
    .vld_out(regslice_both_stream_in_7_V_dest_V_U_vld_out),
    .ack_out(stream_in_7_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_7_V_dest_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 32 ))
regslice_both_mix_out_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(mix_out_TDATA_int_regslice),
    .vld_in(mix_out_TVALID_int_regslice),
    .ack_in(mix_out_TREADY_int_regslice),
    .data_out(mix_out_TDATA),
    .vld_out(regslice_both_mix_out_V_data_V_U_vld_out),
    .ack_out(mix_out_TREADY),
    .apdone_blk(regslice_both_mix_out_V_data_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_mix_out_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(mix_out_TKEEP_int_regslice),
    .vld_in(mix_out_TVALID_int_regslice),
    .ack_in(regslice_both_mix_out_V_keep_V_U_ack_in_dummy),
    .data_out(mix_out_TKEEP),
    .vld_out(regslice_both_mix_out_V_keep_V_U_vld_out),
    .ack_out(mix_out_TREADY),
    .apdone_blk(regslice_both_mix_out_V_keep_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_mix_out_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(mix_out_TSTRB_int_regslice),
    .vld_in(mix_out_TVALID_int_regslice),
    .ack_in(regslice_both_mix_out_V_strb_V_U_ack_in_dummy),
    .data_out(mix_out_TSTRB),
    .vld_out(regslice_both_mix_out_V_strb_V_U_vld_out),
    .ack_out(mix_out_TREADY),
    .apdone_blk(regslice_both_mix_out_V_strb_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 2 ))
regslice_both_mix_out_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(mix_out_TUSER_int_regslice),
    .vld_in(mix_out_TVALID_int_regslice),
    .ack_in(regslice_both_mix_out_V_user_V_U_ack_in_dummy),
    .data_out(mix_out_TUSER),
    .vld_out(regslice_both_mix_out_V_user_V_U_vld_out),
    .ack_out(mix_out_TREADY),
    .apdone_blk(regslice_both_mix_out_V_user_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 1 ))
regslice_both_mix_out_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(mix_out_TLAST_int_regslice),
    .vld_in(mix_out_TVALID_int_regslice),
    .ack_in(regslice_both_mix_out_V_last_V_U_ack_in_dummy),
    .data_out(mix_out_TLAST),
    .vld_out(regslice_both_mix_out_V_last_V_U_vld_out),
    .ack_out(mix_out_TREADY),
    .apdone_blk(regslice_both_mix_out_V_last_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 5 ))
regslice_both_mix_out_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(mix_out_TID_int_regslice),
    .vld_in(mix_out_TVALID_int_regslice),
    .ack_in(regslice_both_mix_out_V_id_V_U_ack_in_dummy),
    .data_out(mix_out_TID),
    .vld_out(regslice_both_mix_out_V_id_V_U_vld_out),
    .ack_out(mix_out_TREADY),
    .apdone_blk(regslice_both_mix_out_V_id_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 6 ))
regslice_both_mix_out_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(mix_out_TDEST_int_regslice),
    .vld_in(mix_out_TVALID_int_regslice),
    .ack_in(regslice_both_mix_out_V_dest_V_U_ack_in_dummy),
    .data_out(mix_out_TDEST),
    .vld_out(regslice_both_mix_out_V_dest_V_U_vld_out),
    .ack_out(mix_out_TREADY),
    .apdone_blk(regslice_both_mix_out_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_ap_start_reg <= 1'b1;
        end else if ((grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_ap_ready == 1'b1)) begin
            grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TVALID == 1'b1))) begin
        mix_out_TDATA_reg <= grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TDATA;
        mix_out_TDEST_reg <= grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TDEST;
        mix_out_TID_reg <= grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TID;
        mix_out_TKEEP_reg <= grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TKEEP;
        mix_out_TLAST_reg <= grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TLAST;
        mix_out_TSTRB_reg <= grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TSTRB;
        mix_out_TUSER_reg <= grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        select_ln61_reg_617 <= select_ln61_fu_559_p3;
        tmp_10_reg_597 <= switches[32'd4];
        tmp_11_reg_602 <= switches[32'd5];
        tmp_12_reg_607 <= switches[32'd6];
        tmp_13_reg_612 <= switches[32'd7];
        tmp_8_reg_587 <= switches[32'd2];
        tmp_9_reg_592 <= switches[32'd3];
        tmp_reg_582 <= switches[32'd1];
        trunc_ln54_reg_577 <= trunc_ln54_fu_395_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((mix_out_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state5)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        mix_out_TDATA_blk_n = mix_out_TREADY_int_regslice;
    end else begin
        mix_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((mix_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        mix_out_TDATA_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_out_pkt_data_out;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TVALID == 1'b1))) begin
        mix_out_TDATA_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TDATA;
    end else begin
        mix_out_TDATA_int_regslice = mix_out_TDATA_reg;
    end
end

always @ (*) begin
    if (((mix_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        mix_out_TDEST_int_regslice = 6'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TVALID == 1'b1))) begin
        mix_out_TDEST_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TDEST;
    end else begin
        mix_out_TDEST_int_regslice = mix_out_TDEST_reg;
    end
end

always @ (*) begin
    if (((mix_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        mix_out_TID_int_regslice = 5'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TVALID == 1'b1))) begin
        mix_out_TID_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TID;
    end else begin
        mix_out_TID_int_regslice = mix_out_TID_reg;
    end
end

always @ (*) begin
    if (((mix_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        mix_out_TKEEP_int_regslice = 4'd15;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TVALID == 1'b1))) begin
        mix_out_TKEEP_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TKEEP;
    end else begin
        mix_out_TKEEP_int_regslice = mix_out_TKEEP_reg;
    end
end

always @ (*) begin
    if (((mix_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        mix_out_TLAST_int_regslice = 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TVALID == 1'b1))) begin
        mix_out_TLAST_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TLAST;
    end else begin
        mix_out_TLAST_int_regslice = mix_out_TLAST_reg;
    end
end

always @ (*) begin
    if (((mix_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        mix_out_TSTRB_int_regslice = 4'd15;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TVALID == 1'b1))) begin
        mix_out_TSTRB_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TSTRB;
    end else begin
        mix_out_TSTRB_int_regslice = mix_out_TSTRB_reg;
    end
end

always @ (*) begin
    if (((mix_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        mix_out_TUSER_int_regslice = 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TVALID == 1'b1))) begin
        mix_out_TUSER_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TUSER;
    end else begin
        mix_out_TUSER_int_regslice = mix_out_TUSER_reg;
    end
end

always @ (*) begin
    if (((mix_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        mix_out_TVALID_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mix_out_TVALID_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TVALID;
    end else begin
        mix_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_in_0_TREADY_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_0_TREADY;
    end else begin
        stream_in_0_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_in_1_TREADY_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_1_TREADY;
    end else begin
        stream_in_1_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_in_2_TREADY_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_2_TREADY;
    end else begin
        stream_in_2_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_in_3_TREADY_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_3_TREADY;
    end else begin
        stream_in_3_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_in_4_TREADY_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_4_TREADY;
    end else begin
        stream_in_4_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_in_5_TREADY_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_5_TREADY;
    end else begin
        stream_in_5_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_in_6_TREADY_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_6_TREADY;
    end else begin
        stream_in_6_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_in_7_TREADY_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_stream_in_7_TREADY;
    end else begin
        stream_in_7_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((mix_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln56_fu_475_p2 = (select_ln55_1_fu_467_p3 + 2'd1);

assign add_ln57_fu_493_p2 = (zext_ln57_fu_489_p1 + 3'd1);

assign add_ln58_fu_507_p2 = (select_ln57_fu_499_p3 + 3'd1);

assign add_ln59_fu_521_p2 = (select_ln58_fu_513_p3 + 3'd1);

assign add_ln60_fu_535_p2 = (select_ln59_fu_527_p3 + 3'd1);

assign add_ln61_fu_553_p2 = (zext_ln61_fu_549_p1 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state5 = ((mix_out_TREADY_int_regslice == 1'b0) | (regslice_both_mix_out_V_data_V_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_ap_start = grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_ap_start_reg;

assign grp_mixer_Pipeline_VITIS_LOOP_30_1_fu_255_mix_out_TREADY = (mix_out_TREADY_int_regslice & ap_CS_fsm_state3);

assign mix_out_TVALID = regslice_both_mix_out_V_data_V_U_vld_out;

assign select_ln55_1_fu_467_p3 = ((tmp_fu_399_p3[0:0] == 1'b1) ? select_ln55_fu_459_p3 : zext_ln55_fu_455_p1);

assign select_ln55_fu_459_p3 = ((trunc_ln54_fu_395_p1[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign select_ln56_fu_481_p3 = ((tmp_8_fu_407_p3[0:0] == 1'b1) ? add_ln56_fu_475_p2 : select_ln55_1_fu_467_p3);

assign select_ln57_fu_499_p3 = ((tmp_9_fu_415_p3[0:0] == 1'b1) ? add_ln57_fu_493_p2 : zext_ln57_fu_489_p1);

assign select_ln58_fu_513_p3 = ((tmp_10_fu_423_p3[0:0] == 1'b1) ? add_ln58_fu_507_p2 : select_ln57_fu_499_p3);

assign select_ln59_fu_527_p3 = ((tmp_11_fu_431_p3[0:0] == 1'b1) ? add_ln59_fu_521_p2 : select_ln58_fu_513_p3);

assign select_ln60_fu_541_p3 = ((tmp_12_fu_439_p3[0:0] == 1'b1) ? add_ln60_fu_535_p2 : select_ln59_fu_527_p3);

assign select_ln61_fu_559_p3 = ((tmp_13_fu_447_p3[0:0] == 1'b1) ? add_ln61_fu_553_p2 : zext_ln61_fu_549_p1);

assign stream_in_0_TREADY = regslice_both_stream_in_0_V_data_V_U_ack_in;

assign stream_in_1_TREADY = regslice_both_stream_in_1_V_data_V_U_ack_in;

assign stream_in_2_TREADY = regslice_both_stream_in_2_V_data_V_U_ack_in;

assign stream_in_3_TREADY = regslice_both_stream_in_3_V_data_V_U_ack_in;

assign stream_in_4_TREADY = regslice_both_stream_in_4_V_data_V_U_ack_in;

assign stream_in_5_TREADY = regslice_both_stream_in_5_V_data_V_U_ack_in;

assign stream_in_6_TREADY = regslice_both_stream_in_6_V_data_V_U_ack_in;

assign stream_in_7_TREADY = regslice_both_stream_in_7_V_data_V_U_ack_in;

assign tmp_10_fu_423_p3 = switches[32'd4];

assign tmp_11_fu_431_p3 = switches[32'd5];

assign tmp_12_fu_439_p3 = switches[32'd6];

assign tmp_13_fu_447_p3 = switches[32'd7];

assign tmp_8_fu_407_p3 = switches[32'd2];

assign tmp_9_fu_415_p3 = switches[32'd3];

assign tmp_fu_399_p3 = switches[32'd1];

assign trunc_ln54_fu_395_p1 = switches[0:0];

assign zext_ln55_fu_455_p1 = trunc_ln54_fu_395_p1;

assign zext_ln57_fu_489_p1 = select_ln56_fu_481_p3;

assign zext_ln61_fu_549_p1 = select_ln60_fu_541_p3;

endmodule //mixer
