

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "8", "9", "10", "11", "12", "13", "14", "15", "16"],
		"CDFG" : "mixer",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "stream_in_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "stream_in",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94", "Port" : "stream_in_V_data_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "stream_in_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "stream_in",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94", "Port" : "stream_in_V_keep_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "stream_in_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "stream_in",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94", "Port" : "stream_in_V_strb_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "stream_in_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "stream_in",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94", "Port" : "stream_in_V_last_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "switches", "Type" : "None", "Direction" : "I"},
			{"Name" : "mix_out_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "mix_out",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94", "Port" : "mix_out_V_data_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "mix_out_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "mix_out",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94", "Port" : "mix_out_V_keep_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "mix_out_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "mix_out",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94", "Port" : "mix_out_V_strb_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "mix_out_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "mix_out",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94", "Port" : "mix_out_V_last_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "current_gain_q16", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "comp_gain_lut", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94", "Port" : "comp_gain_lut", "Inst_start_state" : "2", "Inst_end_state" : "3"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94", "Parent" : "0", "Child" : ["2", "3", "4", "5", "6", "7"],
		"CDFG" : "mixer_Pipeline_VITIS_LOOP_27_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "current_gain_q16_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "mix_out_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "mix_out",
				"BlockSignal" : [
					{"Name" : "mix_out_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "mix_out_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "mix_out"},
			{"Name" : "mix_out_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "mix_out"},
			{"Name" : "mix_out_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "mix_out"},
			{"Name" : "stream_in_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "stream_in",
				"BlockSignal" : [
					{"Name" : "stream_in_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "stream_in_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "stream_in"},
			{"Name" : "stream_in_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "stream_in"},
			{"Name" : "stream_in_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "stream_in"},
			{"Name" : "empty_9", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_10", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_11", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_12", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_13", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_14", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_15", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "active_13", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln49", "Type" : "None", "Direction" : "I"},
			{"Name" : "add_ln68_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "comp_gain_lut", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_27_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94.comp_gain_lut_U", "Parent" : "1"},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94.mul_8s_32s_32_1_1_U1", "Parent" : "1"},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94.mul_20s_24s_32_1_1_U2", "Parent" : "1"},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94.sparsemux_17_4_9_1_1_U3", "Parent" : "1"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94.mul_19s_9ns_28_1_1_U4", "Parent" : "1"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94.flow_control_loop_pipe_sequential_init_U", "Parent" : "1"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_stream_in_V_data_V_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_stream_in_V_keep_V_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_stream_in_V_strb_V_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_stream_in_V_last_V_U", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_mix_out_V_data_V_U", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_mix_out_V_keep_V_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_mix_out_V_strb_V_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_mix_out_V_last_V_U", "Parent" : "0"}]}
