-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mixer_mixer_Pipeline_VITIS_LOOP_30_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    stream_in_0_TVALID : IN STD_LOGIC;
    stream_in_1_TVALID : IN STD_LOGIC;
    stream_in_2_TVALID : IN STD_LOGIC;
    stream_in_3_TVALID : IN STD_LOGIC;
    stream_in_4_TVALID : IN STD_LOGIC;
    stream_in_5_TVALID : IN STD_LOGIC;
    stream_in_6_TVALID : IN STD_LOGIC;
    stream_in_7_TVALID : IN STD_LOGIC;
    mix_out_TREADY : IN STD_LOGIC;
    active_14 : IN STD_LOGIC_VECTOR (3 downto 0);
    mix_out_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    mix_out_TVALID : OUT STD_LOGIC;
    mix_out_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    mix_out_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    mix_out_TUSER : OUT STD_LOGIC_VECTOR (1 downto 0);
    mix_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    mix_out_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
    mix_out_TDEST : OUT STD_LOGIC_VECTOR (5 downto 0);
    stream_in_0_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    stream_in_0_TREADY : OUT STD_LOGIC;
    stream_in_0_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_0_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_0_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
    stream_in_0_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_0_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_in_0_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    stream_in_1_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    stream_in_1_TREADY : OUT STD_LOGIC;
    stream_in_1_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_1_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_1_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
    stream_in_1_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_1_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_in_1_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    stream_in_2_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    stream_in_2_TREADY : OUT STD_LOGIC;
    stream_in_2_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_2_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_2_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
    stream_in_2_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_2_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_in_2_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    stream_in_3_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    stream_in_3_TREADY : OUT STD_LOGIC;
    stream_in_3_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_3_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_3_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
    stream_in_3_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_3_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_in_3_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    stream_in_4_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    stream_in_4_TREADY : OUT STD_LOGIC;
    stream_in_4_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_4_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_4_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
    stream_in_4_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_4_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_in_4_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    stream_in_5_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    stream_in_5_TREADY : OUT STD_LOGIC;
    stream_in_5_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_5_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_5_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
    stream_in_5_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_5_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_in_5_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    stream_in_6_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    stream_in_6_TREADY : OUT STD_LOGIC;
    stream_in_6_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_6_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_6_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
    stream_in_6_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_6_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_in_6_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    stream_in_7_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    stream_in_7_TREADY : OUT STD_LOGIC;
    stream_in_7_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_7_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_7_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
    stream_in_7_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_7_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_in_7_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    empty_16 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_17 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_18 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_19 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_20 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_21 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_22 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty : IN STD_LOGIC_VECTOR (0 downto 0);
    out_pkt_data_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_pkt_data_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of mixer_mixer_Pipeline_VITIS_LOOP_30_1 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv9_B5 : STD_LOGIC_VECTOR (8 downto 0) := "010110101";
    constant ap_const_lv9_94 : STD_LOGIC_VECTOR (8 downto 0) := "010010100";
    constant ap_const_lv9_80 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_const_lv9_72 : STD_LOGIC_VECTOR (8 downto 0) := "001110010";
    constant ap_const_lv9_69 : STD_LOGIC_VECTOR (8 downto 0) := "001101001";
    constant ap_const_lv9_61 : STD_LOGIC_VECTOR (8 downto 0) := "001100001";
    constant ap_const_lv9_5B : STD_LOGIC_VECTOR (8 downto 0) := "001011011";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal or_ln69_6_reg_838 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln69_6_reg_838_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter2_grp1 : BOOLEAN;
    signal or_ln69_6_fu_667_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal mix_out_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal stream_in_0_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal stream_in_1_TDATA_blk_n : STD_LOGIC;
    signal stream_in_2_TDATA_blk_n : STD_LOGIC;
    signal stream_in_3_TDATA_blk_n : STD_LOGIC;
    signal stream_in_4_TDATA_blk_n : STD_LOGIC;
    signal stream_in_5_TDATA_blk_n : STD_LOGIC;
    signal stream_in_6_TDATA_blk_n : STD_LOGIC;
    signal stream_in_7_TDATA_blk_n : STD_LOGIC;
    signal out_pkt_data_reg_492 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal icmp_ln65_fu_509_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_813 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_32_reg_817_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal empty_33_reg_822_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_34_reg_827_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mix_int_8_fu_623_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal mix_int_8_reg_832 : STD_LOGIC_VECTOR (31 downto 0);
    signal mix_int_14_fu_712_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal mix_int_14_reg_842 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_out_pkt_data_phi_fu_496_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter2_out_pkt_data_reg_492 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_out_pkt_data_reg_492 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_out_pkt_data_reg_492 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal mul_ln65_fu_505_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mix_int_fu_567_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal mix_int_1_fu_575_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mix_int_2_fu_581_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal mix_int_3_fu_589_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mix_int_4_fu_595_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal mix_int_5_fu_603_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mix_int_6_fu_609_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal mix_int_7_fu_617_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln69_1_fu_637_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln69_fu_631_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln69_4_fu_655_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln69_3_fu_649_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln69_5_fu_661_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln69_2_fu_643_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal mix_int_9_fu_682_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mix_int_10_fu_687_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal mix_int_11_fu_693_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mix_int_12_fu_699_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal mix_int_13_fu_706_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln65_cast_fu_723_p17 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln65_cast_fu_723_p19 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln65_fu_505_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_loop_init : STD_LOGIC;
    signal mul_ln65_fu_505_p00 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_condition_283 : BOOLEAN;
    signal zext_ln65_cast_fu_723_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln65_cast_fu_723_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln65_cast_fu_723_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln65_cast_fu_723_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln65_cast_fu_723_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln65_cast_fu_723_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln65_cast_fu_723_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln65_cast_fu_723_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component mixer_mul_9ns_32s_40_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (39 downto 0) );
    end component;


    component mixer_sparsemux_17_4_9_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        din2 : IN STD_LOGIC_VECTOR (8 downto 0);
        din3 : IN STD_LOGIC_VECTOR (8 downto 0);
        din4 : IN STD_LOGIC_VECTOR (8 downto 0);
        din5 : IN STD_LOGIC_VECTOR (8 downto 0);
        din6 : IN STD_LOGIC_VECTOR (8 downto 0);
        din7 : IN STD_LOGIC_VECTOR (8 downto 0);
        def : IN STD_LOGIC_VECTOR (8 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component mixer_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_9ns_32s_40_1_1_U1 : component mixer_mul_9ns_32s_40_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 32,
        dout_WIDTH => 40)
    port map (
        din0 => mul_ln65_fu_505_p0,
        din1 => mix_int_14_reg_842,
        dout => mul_ln65_fu_505_p2);

    sparsemux_17_4_9_1_1_U2 : component mixer_sparsemux_17_4_9_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0001",
        din0_WIDTH => 9,
        CASE1 => "0010",
        din1_WIDTH => 9,
        CASE2 => "0011",
        din2_WIDTH => 9,
        CASE3 => "0100",
        din3_WIDTH => 9,
        CASE4 => "0101",
        din4_WIDTH => 9,
        CASE5 => "0110",
        din5_WIDTH => 9,
        CASE6 => "0111",
        din6_WIDTH => 9,
        CASE7 => "1000",
        din7_WIDTH => 9,
        def_WIDTH => 9,
        sel_WIDTH => 4,
        dout_WIDTH => 9)
    port map (
        din0 => ap_const_lv9_100,
        din1 => ap_const_lv9_B5,
        din2 => ap_const_lv9_94,
        din3 => ap_const_lv9_80,
        din4 => ap_const_lv9_72,
        din5 => ap_const_lv9_69,
        din6 => ap_const_lv9_61,
        din7 => ap_const_lv9_5B,
        def => zext_ln65_cast_fu_723_p17,
        sel => active_14,
        dout => zext_ln65_cast_fu_723_p19);

    flow_control_loop_pipe_sequential_init_U : component mixer_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_out_pkt_data_reg_492_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_283)) then
                if ((icmp_ln65_fu_509_p2 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_out_pkt_data_reg_492 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_out_pkt_data_reg_492 <= ap_phi_reg_pp0_iter0_out_pkt_data_reg_492;
                end if;
            end if; 
        end if;
    end process;

    out_pkt_data_reg_492_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln65_reg_813 = ap_const_lv1_0))) then 
                out_pkt_data_reg_492 <= mul_ln65_fu_505_p2(39 downto 8);
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or (not((or_ln69_6_reg_838_pp0_iter1_reg = ap_const_lv1_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
                out_pkt_data_reg_492 <= ap_phi_reg_pp0_iter2_out_pkt_data_reg_492;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                empty_32_reg_817_0 <= stream_in_5_TDATA;
                empty_33_reg_822_0 <= stream_in_6_TDATA;
                empty_34_reg_827_0 <= stream_in_7_TDATA;
                mix_int_8_reg_832 <= mix_int_8_fu_623_p3;
                or_ln69_6_reg_838 <= or_ln69_6_fu_667_p2;
                or_ln69_6_reg_838_pp0_iter1_reg <= or_ln69_6_reg_838;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter2_out_pkt_data_reg_492 <= ap_phi_reg_pp0_iter1_out_pkt_data_reg_492;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln65_reg_813 <= icmp_ln65_fu_509_p2;
                mix_int_14_reg_842 <= mix_int_14_fu_712_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state3_pp0_stage0_iter2_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2_grp1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, stream_in_0_TVALID, stream_in_1_TVALID, stream_in_2_TVALID, stream_in_3_TVALID, stream_in_4_TVALID, stream_in_5_TVALID, stream_in_6_TVALID, stream_in_7_TVALID, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state3_pp0_stage0_iter2_grp1, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_start_int = ap_const_logic_1) and ((stream_in_7_TVALID = ap_const_logic_0) or (stream_in_6_TVALID = ap_const_logic_0) or (stream_in_5_TVALID = ap_const_logic_0) or (stream_in_4_TVALID = ap_const_logic_0) or (stream_in_3_TVALID = ap_const_logic_0) or (stream_in_2_TVALID = ap_const_logic_0) or (stream_in_1_TVALID = ap_const_logic_0) or (stream_in_0_TVALID = ap_const_logic_0))) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2_grp1)));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state3_pp0_stage0_iter2_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2_grp1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, stream_in_0_TVALID, stream_in_1_TVALID, stream_in_2_TVALID, stream_in_3_TVALID, stream_in_4_TVALID, stream_in_5_TVALID, stream_in_6_TVALID, stream_in_7_TVALID, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state3_pp0_stage0_iter2_grp1, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_start_int = ap_const_logic_1) and ((stream_in_7_TVALID = ap_const_logic_0) or (stream_in_6_TVALID = ap_const_logic_0) or (stream_in_5_TVALID = ap_const_logic_0) or (stream_in_4_TVALID = ap_const_logic_0) or (stream_in_3_TVALID = ap_const_logic_0) or (stream_in_2_TVALID = ap_const_logic_0) or (stream_in_1_TVALID = ap_const_logic_0) or (stream_in_0_TVALID = ap_const_logic_0))) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2_grp1)));
    end process;


    ap_block_pp0_stage0_subdone_grp1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state3_pp0_stage0_iter2_grp1)
    begin
                ap_block_pp0_stage0_subdone_grp1 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2_grp1));
    end process;


    ap_block_state3_pp0_stage0_iter2_grp1_assign_proc : process(mix_out_TREADY, or_ln69_6_reg_838_pp0_iter1_reg)
    begin
                ap_block_state3_pp0_stage0_iter2_grp1 <= ((or_ln69_6_reg_838_pp0_iter1_reg = ap_const_lv1_0) and (mix_out_TREADY = ap_const_logic_0));
    end process;


    ap_condition_283_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1, ap_start_int)
    begin
                ap_condition_283 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, or_ln69_6_fu_667_p2, ap_start_int)
    begin
        if (((or_ln69_6_fu_667_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter2_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_out_pkt_data_phi_fu_496_p4_assign_proc : process(icmp_ln65_reg_813, ap_phi_reg_pp0_iter2_out_pkt_data_reg_492, mul_ln65_fu_505_p2)
    begin
        if ((icmp_ln65_reg_813 = ap_const_lv1_0)) then 
            ap_phi_mux_out_pkt_data_phi_fu_496_p4 <= mul_ln65_fu_505_p2(39 downto 8);
        else 
            ap_phi_mux_out_pkt_data_phi_fu_496_p4 <= ap_phi_reg_pp0_iter2_out_pkt_data_reg_492;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_out_pkt_data_reg_492 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln65_fu_509_p2 <= "1" when (active_14 = ap_const_lv4_0) else "0";
    mix_int_10_fu_687_p3 <= 
        mix_int_9_fu_682_p2 when (empty_21(0) = '1') else 
        mix_int_8_reg_832;
    mix_int_11_fu_693_p2 <= std_logic_vector(unsigned(empty_33_reg_822_0) + unsigned(mix_int_10_fu_687_p3));
    mix_int_12_fu_699_p3 <= 
        mix_int_11_fu_693_p2 when (empty_22(0) = '1') else 
        mix_int_10_fu_687_p3;
    mix_int_13_fu_706_p2 <= std_logic_vector(unsigned(empty_34_reg_827_0) + unsigned(mix_int_12_fu_699_p3));
    mix_int_14_fu_712_p3 <= 
        mix_int_13_fu_706_p2 when (empty(0) = '1') else 
        mix_int_12_fu_699_p3;
    mix_int_1_fu_575_p2 <= std_logic_vector(unsigned(stream_in_1_TDATA) + unsigned(mix_int_fu_567_p3));
    mix_int_2_fu_581_p3 <= 
        mix_int_1_fu_575_p2 when (empty_17(0) = '1') else 
        mix_int_fu_567_p3;
    mix_int_3_fu_589_p2 <= std_logic_vector(unsigned(stream_in_2_TDATA) + unsigned(mix_int_2_fu_581_p3));
    mix_int_4_fu_595_p3 <= 
        mix_int_3_fu_589_p2 when (empty_18(0) = '1') else 
        mix_int_2_fu_581_p3;
    mix_int_5_fu_603_p2 <= std_logic_vector(unsigned(stream_in_3_TDATA) + unsigned(mix_int_4_fu_595_p3));
    mix_int_6_fu_609_p3 <= 
        mix_int_5_fu_603_p2 when (empty_19(0) = '1') else 
        mix_int_4_fu_595_p3;
    mix_int_7_fu_617_p2 <= std_logic_vector(unsigned(stream_in_4_TDATA) + unsigned(mix_int_6_fu_609_p3));
    mix_int_8_fu_623_p3 <= 
        mix_int_7_fu_617_p2 when (empty_20(0) = '1') else 
        mix_int_6_fu_609_p3;
    mix_int_9_fu_682_p2 <= std_logic_vector(unsigned(empty_32_reg_817_0) + unsigned(mix_int_8_reg_832));
    mix_int_fu_567_p3 <= 
        stream_in_0_TDATA when (empty_16(0) = '1') else 
        ap_const_lv32_0;
    mix_out_TDATA <= ap_phi_mux_out_pkt_data_phi_fu_496_p4;

    mix_out_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, mix_out_TREADY, ap_block_pp0_stage0_subdone_grp1_done_reg, or_ln69_6_reg_838_pp0_iter1_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((or_ln69_6_reg_838_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            mix_out_TDATA_blk_n <= mix_out_TREADY;
        else 
            mix_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    mix_out_TDEST <= ap_const_lv6_0;
    mix_out_TID <= ap_const_lv5_0;
    mix_out_TKEEP <= ap_const_lv4_F;
    mix_out_TLAST <= ap_const_lv1_0;
    mix_out_TSTRB <= ap_const_lv4_F;
    mix_out_TUSER <= ap_const_lv2_0;

    mix_out_TVALID_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone_grp1_done_reg, or_ln69_6_reg_838_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((or_ln69_6_reg_838_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            mix_out_TVALID <= ap_const_logic_1;
        else 
            mix_out_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln65_fu_505_p0 <= mul_ln65_fu_505_p00(9 - 1 downto 0);
    mul_ln65_fu_505_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln65_cast_fu_723_p19),40));
    or_ln69_1_fu_637_p2 <= (stream_in_5_TLAST or stream_in_4_TLAST);
    or_ln69_2_fu_643_p2 <= (or_ln69_fu_631_p2 or or_ln69_1_fu_637_p2);
    or_ln69_3_fu_649_p2 <= (stream_in_1_TLAST or stream_in_0_TLAST);
    or_ln69_4_fu_655_p2 <= (stream_in_3_TLAST or stream_in_2_TLAST);
    or_ln69_5_fu_661_p2 <= (or_ln69_4_fu_655_p2 or or_ln69_3_fu_649_p2);
    or_ln69_6_fu_667_p2 <= (or_ln69_5_fu_661_p2 or or_ln69_2_fu_643_p2);
    or_ln69_fu_631_p2 <= (stream_in_7_TLAST or stream_in_6_TLAST);
    out_pkt_data_out <= out_pkt_data_reg_492;

    out_pkt_data_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg, or_ln69_6_reg_838_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp1, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((or_ln69_6_reg_838_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            out_pkt_data_out_ap_vld <= ap_const_logic_1;
        else 
            out_pkt_data_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    stream_in_0_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, stream_in_0_TVALID, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_0_TDATA_blk_n <= stream_in_0_TVALID;
        else 
            stream_in_0_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_in_0_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_0_TREADY <= ap_const_logic_1;
        else 
            stream_in_0_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    stream_in_1_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, stream_in_1_TVALID, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_1_TDATA_blk_n <= stream_in_1_TVALID;
        else 
            stream_in_1_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_in_1_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_1_TREADY <= ap_const_logic_1;
        else 
            stream_in_1_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    stream_in_2_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, stream_in_2_TVALID, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_2_TDATA_blk_n <= stream_in_2_TVALID;
        else 
            stream_in_2_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_in_2_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_2_TREADY <= ap_const_logic_1;
        else 
            stream_in_2_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    stream_in_3_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, stream_in_3_TVALID, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_3_TDATA_blk_n <= stream_in_3_TVALID;
        else 
            stream_in_3_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_in_3_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_3_TREADY <= ap_const_logic_1;
        else 
            stream_in_3_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    stream_in_4_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, stream_in_4_TVALID, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_4_TDATA_blk_n <= stream_in_4_TVALID;
        else 
            stream_in_4_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_in_4_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_4_TREADY <= ap_const_logic_1;
        else 
            stream_in_4_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    stream_in_5_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, stream_in_5_TVALID, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_5_TDATA_blk_n <= stream_in_5_TVALID;
        else 
            stream_in_5_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_in_5_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_5_TREADY <= ap_const_logic_1;
        else 
            stream_in_5_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    stream_in_6_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, stream_in_6_TVALID, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_6_TDATA_blk_n <= stream_in_6_TVALID;
        else 
            stream_in_6_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_in_6_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_6_TREADY <= ap_const_logic_1;
        else 
            stream_in_6_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    stream_in_7_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, stream_in_7_TVALID, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_7_TDATA_blk_n <= stream_in_7_TVALID;
        else 
            stream_in_7_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_in_7_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_7_TREADY <= ap_const_logic_1;
        else 
            stream_in_7_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln65_cast_fu_723_p17 <= "XXXXXXXXX";
end behav;
