-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mixer is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    stream_in_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    stream_in_TVALID : IN STD_LOGIC;
    stream_in_TREADY : OUT STD_LOGIC;
    stream_in_TKEEP : IN STD_LOGIC_VECTOR (15 downto 0);
    stream_in_TSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
    stream_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    switches : IN STD_LOGIC_VECTOR (7 downto 0);
    mix_out_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    mix_out_TVALID : OUT STD_LOGIC;
    mix_out_TREADY : IN STD_LOGIC;
    mix_out_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    mix_out_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    mix_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of mixer is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "mixer_mixer,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sfvc784-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.255500,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=467,HLS_SYN_LUT=1014,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal current_gain_q16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000010000000000000000";
    signal trunc_ln42_fu_128_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_reg_312 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_132_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_317 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_140_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_reg_322 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_148_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_reg_327 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_156_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_reg_332 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_fu_164_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_reg_337 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_172_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_reg_342 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_reg_347 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln48_fu_274_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln48_reg_352 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln49_fu_290_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln49_reg_361 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_start : STD_LOGIC;
    signal grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_done : STD_LOGIC;
    signal grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_idle : STD_LOGIC;
    signal grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_ready : STD_LOGIC;
    signal grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TREADY : STD_LOGIC;
    signal grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID : STD_LOGIC;
    signal grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_stream_in_TREADY : STD_LOGIC;
    signal grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_add_ln68_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_add_ln68_out_ap_vld : STD_LOGIC;
    signal grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal mix_out_TDATA_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mix_out_TKEEP_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal mix_out_TSTRB_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal mix_out_TLAST_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal regslice_both_mix_out_V_data_V_U_apdone_blk : STD_LOGIC;
    signal select_ln43_fu_192_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln43_fu_188_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln43_1_fu_200_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln44_fu_208_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln44_fu_214_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln45_fu_222_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln45_fu_226_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln45_fu_232_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln46_fu_240_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln46_fu_246_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln47_fu_254_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln47_fu_260_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln48_fu_268_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln49_fu_287_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal regslice_both_stream_in_V_data_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_TDATA_int_regslice : STD_LOGIC_VECTOR (127 downto 0);
    signal stream_in_TVALID_int_regslice : STD_LOGIC;
    signal stream_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_stream_in_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_TKEEP_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal regslice_both_stream_in_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_TSTRB_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal regslice_both_stream_in_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_V_last_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_stream_in_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_V_last_V_U_ack_in : STD_LOGIC;
    signal mix_out_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal mix_out_TVALID_int_regslice : STD_LOGIC;
    signal mix_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_mix_out_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_mix_out_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal mix_out_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_mix_out_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_mix_out_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_mix_out_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal mix_out_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_mix_out_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_mix_out_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_mix_out_V_last_V_U_apdone_blk : STD_LOGIC;
    signal mix_out_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_mix_out_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_mix_out_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mixer_mixer_Pipeline_VITIS_LOOP_27_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_in_TVALID : IN STD_LOGIC;
        mix_out_TREADY : IN STD_LOGIC;
        current_gain_q16_load : IN STD_LOGIC_VECTOR (31 downto 0);
        mix_out_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        mix_out_TVALID : OUT STD_LOGIC;
        mix_out_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        mix_out_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        mix_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        stream_in_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        stream_in_TREADY : OUT STD_LOGIC;
        stream_in_TKEEP : IN STD_LOGIC_VECTOR (15 downto 0);
        stream_in_TSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
        stream_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        empty_9 : IN STD_LOGIC_VECTOR (0 downto 0);
        empty_10 : IN STD_LOGIC_VECTOR (0 downto 0);
        empty_11 : IN STD_LOGIC_VECTOR (0 downto 0);
        empty_12 : IN STD_LOGIC_VECTOR (0 downto 0);
        empty_13 : IN STD_LOGIC_VECTOR (0 downto 0);
        empty_14 : IN STD_LOGIC_VECTOR (0 downto 0);
        empty_15 : IN STD_LOGIC_VECTOR (0 downto 0);
        empty : IN STD_LOGIC_VECTOR (0 downto 0);
        active_13 : IN STD_LOGIC_VECTOR (3 downto 0);
        zext_ln49 : IN STD_LOGIC_VECTOR (2 downto 0);
        add_ln68_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add_ln68_out_ap_vld : OUT STD_LOGIC );
    end component;


    component mixer_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component mixer_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94 : component mixer_mixer_Pipeline_VITIS_LOOP_27_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_start,
        ap_done => grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_done,
        ap_idle => grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_idle,
        ap_ready => grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_ready,
        stream_in_TVALID => stream_in_TVALID_int_regslice,
        mix_out_TREADY => grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TREADY,
        current_gain_q16_load => current_gain_q16,
        mix_out_TDATA => grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TDATA,
        mix_out_TVALID => grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID,
        mix_out_TKEEP => grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TKEEP,
        mix_out_TSTRB => grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TSTRB,
        mix_out_TLAST => grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TLAST,
        stream_in_TDATA => stream_in_TDATA_int_regslice,
        stream_in_TREADY => grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_stream_in_TREADY,
        stream_in_TKEEP => stream_in_TKEEP_int_regslice,
        stream_in_TSTRB => stream_in_TSTRB_int_regslice,
        stream_in_TLAST => stream_in_TLAST_int_regslice,
        empty_9 => trunc_ln42_reg_312,
        empty_10 => tmp_reg_317,
        empty_11 => tmp_12_reg_322,
        empty_12 => tmp_13_reg_327,
        empty_13 => tmp_14_reg_332,
        empty_14 => tmp_15_reg_337,
        empty_15 => tmp_16_reg_342,
        empty => tmp_17_reg_347,
        active_13 => add_ln49_reg_361,
        zext_ln49 => select_ln48_reg_352,
        add_ln68_out => grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_add_ln68_out,
        add_ln68_out_ap_vld => grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_add_ln68_out_ap_vld);

    control_s_axi_U : component mixer_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    regslice_both_stream_in_V_data_V_U : component mixer_regslice_both
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_TDATA,
        vld_in => stream_in_TVALID,
        ack_in => regslice_both_stream_in_V_data_V_U_ack_in,
        data_out => stream_in_TDATA_int_regslice,
        vld_out => stream_in_TVALID_int_regslice,
        ack_out => stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_V_data_V_U_apdone_blk);

    regslice_both_stream_in_V_keep_V_U : component mixer_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_TKEEP,
        vld_in => stream_in_TVALID,
        ack_in => regslice_both_stream_in_V_keep_V_U_ack_in,
        data_out => stream_in_TKEEP_int_regslice,
        vld_out => regslice_both_stream_in_V_keep_V_U_vld_out,
        ack_out => stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_V_keep_V_U_apdone_blk);

    regslice_both_stream_in_V_strb_V_U : component mixer_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_TSTRB,
        vld_in => stream_in_TVALID,
        ack_in => regslice_both_stream_in_V_strb_V_U_ack_in,
        data_out => stream_in_TSTRB_int_regslice,
        vld_out => regslice_both_stream_in_V_strb_V_U_vld_out,
        ack_out => stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_V_strb_V_U_apdone_blk);

    regslice_both_stream_in_V_last_V_U : component mixer_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_TLAST,
        vld_in => stream_in_TVALID,
        ack_in => regslice_both_stream_in_V_last_V_U_ack_in,
        data_out => stream_in_TLAST_int_regslice,
        vld_out => regslice_both_stream_in_V_last_V_U_vld_out,
        ack_out => stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_V_last_V_U_apdone_blk);

    regslice_both_mix_out_V_data_V_U : component mixer_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => mix_out_TDATA_int_regslice,
        vld_in => grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID,
        ack_in => mix_out_TREADY_int_regslice,
        data_out => mix_out_TDATA,
        vld_out => regslice_both_mix_out_V_data_V_U_vld_out,
        ack_out => mix_out_TREADY,
        apdone_blk => regslice_both_mix_out_V_data_V_U_apdone_blk);

    regslice_both_mix_out_V_keep_V_U : component mixer_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => mix_out_TKEEP_int_regslice,
        vld_in => grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID,
        ack_in => regslice_both_mix_out_V_keep_V_U_ack_in_dummy,
        data_out => mix_out_TKEEP,
        vld_out => regslice_both_mix_out_V_keep_V_U_vld_out,
        ack_out => mix_out_TREADY,
        apdone_blk => regslice_both_mix_out_V_keep_V_U_apdone_blk);

    regslice_both_mix_out_V_strb_V_U : component mixer_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => mix_out_TSTRB_int_regslice,
        vld_in => grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID,
        ack_in => regslice_both_mix_out_V_strb_V_U_ack_in_dummy,
        data_out => mix_out_TSTRB,
        vld_out => regslice_both_mix_out_V_strb_V_U_vld_out,
        ack_out => mix_out_TREADY,
        apdone_blk => regslice_both_mix_out_V_strb_V_U_apdone_blk);

    regslice_both_mix_out_V_last_V_U : component mixer_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => mix_out_TLAST_int_regslice,
        vld_in => grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID,
        ack_in => regslice_both_mix_out_V_last_V_U_ack_in_dummy,
        data_out => mix_out_TLAST,
        vld_out => regslice_both_mix_out_V_last_V_U_vld_out,
        ack_out => mix_out_TREADY,
        apdone_blk => regslice_both_mix_out_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_ready = ap_const_logic_1)) then 
                    grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln49_reg_361 <= add_ln49_fu_290_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (regslice_both_mix_out_V_data_V_U_apdone_blk = ap_const_logic_0))) then
                current_gain_q16 <= grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_add_ln68_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                mix_out_TDATA_reg <= grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TDATA;
                mix_out_TKEEP_reg <= grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TKEEP;
                mix_out_TLAST_reg <= grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TLAST;
                mix_out_TSTRB_reg <= grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TSTRB;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                select_ln48_reg_352 <= select_ln48_fu_274_p3;
                tmp_12_reg_322 <= switches(2 downto 2);
                tmp_13_reg_327 <= switches(3 downto 3);
                tmp_14_reg_332 <= switches(4 downto 4);
                tmp_15_reg_337 <= switches(5 downto 5);
                tmp_16_reg_342 <= switches(6 downto 6);
                tmp_17_reg_347 <= switches(7 downto 7);
                tmp_reg_317 <= switches(1 downto 1);
                trunc_ln42_reg_312 <= trunc_ln42_fu_128_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state4, regslice_both_mix_out_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (regslice_both_mix_out_V_data_V_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln44_fu_208_p2 <= std_logic_vector(unsigned(select_ln43_1_fu_200_p3) + unsigned(ap_const_lv2_1));
    add_ln45_fu_226_p2 <= std_logic_vector(unsigned(zext_ln45_fu_222_p1) + unsigned(ap_const_lv3_1));
    add_ln46_fu_240_p2 <= std_logic_vector(unsigned(select_ln45_fu_232_p3) + unsigned(ap_const_lv3_1));
    add_ln47_fu_254_p2 <= std_logic_vector(unsigned(select_ln46_fu_246_p3) + unsigned(ap_const_lv3_1));
    add_ln48_fu_268_p2 <= std_logic_vector(unsigned(select_ln47_fu_260_p3) + unsigned(ap_const_lv3_1));
    add_ln49_fu_290_p2 <= std_logic_vector(unsigned(zext_ln49_fu_287_p1) + unsigned(ap_const_lv4_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_done)
    begin
        if ((grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(regslice_both_mix_out_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_mix_out_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state4, regslice_both_mix_out_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (regslice_both_mix_out_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4, regslice_both_mix_out_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (regslice_both_mix_out_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_start <= grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_start_reg;
    grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TREADY <= (mix_out_TREADY_int_regslice and ap_CS_fsm_state3);

    mix_out_TDATA_int_regslice_assign_proc : process(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TDATA, grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID, ap_CS_fsm_state3, mix_out_TDATA_reg)
    begin
        if (((grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            mix_out_TDATA_int_regslice <= grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TDATA;
        else 
            mix_out_TDATA_int_regslice <= mix_out_TDATA_reg;
        end if; 
    end process;


    mix_out_TKEEP_int_regslice_assign_proc : process(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID, grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TKEEP, ap_CS_fsm_state3, mix_out_TKEEP_reg)
    begin
        if (((grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            mix_out_TKEEP_int_regslice <= grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TKEEP;
        else 
            mix_out_TKEEP_int_regslice <= mix_out_TKEEP_reg;
        end if; 
    end process;


    mix_out_TLAST_int_regslice_assign_proc : process(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID, grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TLAST, ap_CS_fsm_state3, mix_out_TLAST_reg)
    begin
        if (((grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            mix_out_TLAST_int_regslice <= grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TLAST;
        else 
            mix_out_TLAST_int_regslice <= mix_out_TLAST_reg;
        end if; 
    end process;


    mix_out_TSTRB_int_regslice_assign_proc : process(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID, grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TSTRB, ap_CS_fsm_state3, mix_out_TSTRB_reg)
    begin
        if (((grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            mix_out_TSTRB_int_regslice <= grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TSTRB;
        else 
            mix_out_TSTRB_int_regslice <= mix_out_TSTRB_reg;
        end if; 
    end process;

    mix_out_TVALID <= regslice_both_mix_out_V_data_V_U_vld_out;
    mix_out_TVALID_int_regslice <= grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID;
    select_ln43_1_fu_200_p3 <= 
        select_ln43_fu_192_p3 when (tmp_fu_132_p3(0) = '1') else 
        zext_ln43_fu_188_p1;
    select_ln43_fu_192_p3 <= 
        ap_const_lv2_2 when (trunc_ln42_fu_128_p1(0) = '1') else 
        ap_const_lv2_1;
    select_ln44_fu_214_p3 <= 
        add_ln44_fu_208_p2 when (tmp_12_fu_140_p3(0) = '1') else 
        select_ln43_1_fu_200_p3;
    select_ln45_fu_232_p3 <= 
        add_ln45_fu_226_p2 when (tmp_13_fu_148_p3(0) = '1') else 
        zext_ln45_fu_222_p1;
    select_ln46_fu_246_p3 <= 
        add_ln46_fu_240_p2 when (tmp_14_fu_156_p3(0) = '1') else 
        select_ln45_fu_232_p3;
    select_ln47_fu_260_p3 <= 
        add_ln47_fu_254_p2 when (tmp_15_fu_164_p3(0) = '1') else 
        select_ln46_fu_246_p3;
    select_ln48_fu_274_p3 <= 
        add_ln48_fu_268_p2 when (tmp_16_fu_172_p3(0) = '1') else 
        select_ln47_fu_260_p3;
    stream_in_TREADY <= regslice_both_stream_in_V_data_V_U_ack_in;

    stream_in_TREADY_int_regslice_assign_proc : process(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_stream_in_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            stream_in_TREADY_int_regslice <= grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_stream_in_TREADY;
        else 
            stream_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    tmp_12_fu_140_p3 <= switches(2 downto 2);
    tmp_13_fu_148_p3 <= switches(3 downto 3);
    tmp_14_fu_156_p3 <= switches(4 downto 4);
    tmp_15_fu_164_p3 <= switches(5 downto 5);
    tmp_16_fu_172_p3 <= switches(6 downto 6);
    tmp_fu_132_p3 <= switches(1 downto 1);
    trunc_ln42_fu_128_p1 <= switches(1 - 1 downto 0);
    zext_ln43_fu_188_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln42_fu_128_p1),2));
    zext_ln45_fu_222_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln44_fu_214_p3),3));
    zext_ln49_fu_287_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln48_reg_352),4));
end behav;
