// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mixer_mixer,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sfvc784-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.255500,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=467,HLS_SYN_LUT=1014,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module mixer (
        ap_clk,
        ap_rst_n,
        stream_in_TDATA,
        stream_in_TVALID,
        stream_in_TREADY,
        stream_in_TKEEP,
        stream_in_TSTRB,
        stream_in_TLAST,
        switches,
        mix_out_TDATA,
        mix_out_TVALID,
        mix_out_TREADY,
        mix_out_TKEEP,
        mix_out_TSTRB,
        mix_out_TLAST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [127:0] stream_in_TDATA;
input   stream_in_TVALID;
output   stream_in_TREADY;
input  [15:0] stream_in_TKEEP;
input  [15:0] stream_in_TSTRB;
input  [0:0] stream_in_TLAST;
input  [7:0] switches;
output  [31:0] mix_out_TDATA;
output   mix_out_TVALID;
input   mix_out_TREADY;
output  [3:0] mix_out_TKEEP;
output  [3:0] mix_out_TSTRB;
output  [0:0] mix_out_TLAST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [31:0] current_gain_q16;
wire   [0:0] trunc_ln42_fu_128_p1;
reg   [0:0] trunc_ln42_reg_312;
wire   [0:0] tmp_fu_132_p3;
reg   [0:0] tmp_reg_317;
wire   [0:0] tmp_12_fu_140_p3;
reg   [0:0] tmp_12_reg_322;
wire   [0:0] tmp_13_fu_148_p3;
reg   [0:0] tmp_13_reg_327;
wire   [0:0] tmp_14_fu_156_p3;
reg   [0:0] tmp_14_reg_332;
wire   [0:0] tmp_15_fu_164_p3;
reg   [0:0] tmp_15_reg_337;
wire   [0:0] tmp_16_fu_172_p3;
reg   [0:0] tmp_16_reg_342;
reg   [0:0] tmp_17_reg_347;
wire   [2:0] select_ln48_fu_274_p3;
reg   [2:0] select_ln48_reg_352;
wire   [3:0] add_ln49_fu_290_p2;
reg   [3:0] add_ln49_reg_361;
wire    ap_CS_fsm_state2;
wire    grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_start;
wire    grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_done;
wire    grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_idle;
wire    grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_ready;
wire    grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TREADY;
wire   [31:0] grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TDATA;
wire    grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID;
wire   [3:0] grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TKEEP;
wire   [3:0] grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TSTRB;
wire   [0:0] grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TLAST;
wire    grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_stream_in_TREADY;
wire   [31:0] grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_add_ln68_out;
wire    grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_add_ln68_out_ap_vld;
reg    grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [31:0] mix_out_TDATA_reg;
reg   [3:0] mix_out_TKEEP_reg;
reg   [3:0] mix_out_TSTRB_reg;
reg   [0:0] mix_out_TLAST_reg;
wire    ap_CS_fsm_state4;
wire    regslice_both_mix_out_V_data_V_U_apdone_blk;
wire   [1:0] select_ln43_fu_192_p3;
wire   [1:0] zext_ln43_fu_188_p1;
wire   [1:0] select_ln43_1_fu_200_p3;
wire   [1:0] add_ln44_fu_208_p2;
wire   [1:0] select_ln44_fu_214_p3;
wire   [2:0] zext_ln45_fu_222_p1;
wire   [2:0] add_ln45_fu_226_p2;
wire   [2:0] select_ln45_fu_232_p3;
wire   [2:0] add_ln46_fu_240_p2;
wire   [2:0] select_ln46_fu_246_p3;
wire   [2:0] add_ln47_fu_254_p2;
wire   [2:0] select_ln47_fu_260_p3;
wire   [2:0] add_ln48_fu_268_p2;
wire   [3:0] zext_ln49_fu_287_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    regslice_both_stream_in_V_data_V_U_apdone_blk;
wire   [127:0] stream_in_TDATA_int_regslice;
wire    stream_in_TVALID_int_regslice;
reg    stream_in_TREADY_int_regslice;
wire    regslice_both_stream_in_V_data_V_U_ack_in;
wire    regslice_both_stream_in_V_keep_V_U_apdone_blk;
wire   [15:0] stream_in_TKEEP_int_regslice;
wire    regslice_both_stream_in_V_keep_V_U_vld_out;
wire    regslice_both_stream_in_V_keep_V_U_ack_in;
wire    regslice_both_stream_in_V_strb_V_U_apdone_blk;
wire   [15:0] stream_in_TSTRB_int_regslice;
wire    regslice_both_stream_in_V_strb_V_U_vld_out;
wire    regslice_both_stream_in_V_strb_V_U_ack_in;
wire    regslice_both_stream_in_V_last_V_U_apdone_blk;
wire   [0:0] stream_in_TLAST_int_regslice;
wire    regslice_both_stream_in_V_last_V_U_vld_out;
wire    regslice_both_stream_in_V_last_V_U_ack_in;
reg   [31:0] mix_out_TDATA_int_regslice;
wire    mix_out_TVALID_int_regslice;
wire    mix_out_TREADY_int_regslice;
wire    regslice_both_mix_out_V_data_V_U_vld_out;
wire    regslice_both_mix_out_V_keep_V_U_apdone_blk;
reg   [3:0] mix_out_TKEEP_int_regslice;
wire    regslice_both_mix_out_V_keep_V_U_ack_in_dummy;
wire    regslice_both_mix_out_V_keep_V_U_vld_out;
wire    regslice_both_mix_out_V_strb_V_U_apdone_blk;
reg   [3:0] mix_out_TSTRB_int_regslice;
wire    regslice_both_mix_out_V_strb_V_U_ack_in_dummy;
wire    regslice_both_mix_out_V_strb_V_U_vld_out;
wire    regslice_both_mix_out_V_last_V_U_apdone_blk;
reg   [0:0] mix_out_TLAST_int_regslice;
wire    regslice_both_mix_out_V_last_V_U_ack_in_dummy;
wire    regslice_both_mix_out_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 current_gain_q16 = 32'd65536;
#0 grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_start_reg = 1'b0;
end

mixer_mixer_Pipeline_VITIS_LOOP_27_1 grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_start),
    .ap_done(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_done),
    .ap_idle(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_idle),
    .ap_ready(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_ready),
    .stream_in_TVALID(stream_in_TVALID_int_regslice),
    .mix_out_TREADY(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TREADY),
    .current_gain_q16_load(current_gain_q16),
    .mix_out_TDATA(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TDATA),
    .mix_out_TVALID(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID),
    .mix_out_TKEEP(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TKEEP),
    .mix_out_TSTRB(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TSTRB),
    .mix_out_TLAST(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TLAST),
    .stream_in_TDATA(stream_in_TDATA_int_regslice),
    .stream_in_TREADY(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_stream_in_TREADY),
    .stream_in_TKEEP(stream_in_TKEEP_int_regslice),
    .stream_in_TSTRB(stream_in_TSTRB_int_regslice),
    .stream_in_TLAST(stream_in_TLAST_int_regslice),
    .empty_9(trunc_ln42_reg_312),
    .empty_10(tmp_reg_317),
    .empty_11(tmp_12_reg_322),
    .empty_12(tmp_13_reg_327),
    .empty_13(tmp_14_reg_332),
    .empty_14(tmp_15_reg_337),
    .empty_15(tmp_16_reg_342),
    .empty(tmp_17_reg_347),
    .active_13(add_ln49_reg_361),
    .zext_ln49(select_ln48_reg_352),
    .add_ln68_out(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_add_ln68_out),
    .add_ln68_out_ap_vld(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_add_ln68_out_ap_vld)
);

mixer_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

mixer_regslice_both #(
    .DataWidth( 128 ))
regslice_both_stream_in_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_TDATA),
    .vld_in(stream_in_TVALID),
    .ack_in(regslice_both_stream_in_V_data_V_U_ack_in),
    .data_out(stream_in_TDATA_int_regslice),
    .vld_out(stream_in_TVALID_int_regslice),
    .ack_out(stream_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_V_data_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 16 ))
regslice_both_stream_in_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_TKEEP),
    .vld_in(stream_in_TVALID),
    .ack_in(regslice_both_stream_in_V_keep_V_U_ack_in),
    .data_out(stream_in_TKEEP_int_regslice),
    .vld_out(regslice_both_stream_in_V_keep_V_U_vld_out),
    .ack_out(stream_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_V_keep_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 16 ))
regslice_both_stream_in_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_TSTRB),
    .vld_in(stream_in_TVALID),
    .ack_in(regslice_both_stream_in_V_strb_V_U_ack_in),
    .data_out(stream_in_TSTRB_int_regslice),
    .vld_out(regslice_both_stream_in_V_strb_V_U_vld_out),
    .ack_out(stream_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_V_strb_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_TLAST),
    .vld_in(stream_in_TVALID),
    .ack_in(regslice_both_stream_in_V_last_V_U_ack_in),
    .data_out(stream_in_TLAST_int_regslice),
    .vld_out(regslice_both_stream_in_V_last_V_U_vld_out),
    .ack_out(stream_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_V_last_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 32 ))
regslice_both_mix_out_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(mix_out_TDATA_int_regslice),
    .vld_in(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID),
    .ack_in(mix_out_TREADY_int_regslice),
    .data_out(mix_out_TDATA),
    .vld_out(regslice_both_mix_out_V_data_V_U_vld_out),
    .ack_out(mix_out_TREADY),
    .apdone_blk(regslice_both_mix_out_V_data_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_mix_out_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(mix_out_TKEEP_int_regslice),
    .vld_in(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID),
    .ack_in(regslice_both_mix_out_V_keep_V_U_ack_in_dummy),
    .data_out(mix_out_TKEEP),
    .vld_out(regslice_both_mix_out_V_keep_V_U_vld_out),
    .ack_out(mix_out_TREADY),
    .apdone_blk(regslice_both_mix_out_V_keep_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_mix_out_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(mix_out_TSTRB_int_regslice),
    .vld_in(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID),
    .ack_in(regslice_both_mix_out_V_strb_V_U_ack_in_dummy),
    .data_out(mix_out_TSTRB),
    .vld_out(regslice_both_mix_out_V_strb_V_U_vld_out),
    .ack_out(mix_out_TREADY),
    .apdone_blk(regslice_both_mix_out_V_strb_V_U_apdone_blk)
);

mixer_regslice_both #(
    .DataWidth( 1 ))
regslice_both_mix_out_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(mix_out_TLAST_int_regslice),
    .vld_in(grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID),
    .ack_in(regslice_both_mix_out_V_last_V_U_ack_in_dummy),
    .data_out(mix_out_TLAST),
    .vld_out(regslice_both_mix_out_V_last_V_U_vld_out),
    .ack_out(mix_out_TREADY),
    .apdone_blk(regslice_both_mix_out_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_start_reg <= 1'b1;
        end else if ((grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_ready == 1'b1)) begin
            grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln49_reg_361 <= add_ln49_fu_290_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_mix_out_V_data_V_U_apdone_blk == 1'b0))) begin
        current_gain_q16 <= grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_add_ln68_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        mix_out_TDATA_reg <= grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TDATA;
        mix_out_TKEEP_reg <= grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TKEEP;
        mix_out_TLAST_reg <= grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TLAST;
        mix_out_TSTRB_reg <= grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        select_ln48_reg_352 <= select_ln48_fu_274_p3;
        tmp_12_reg_322 <= switches[32'd2];
        tmp_13_reg_327 <= switches[32'd3];
        tmp_14_reg_332 <= switches[32'd4];
        tmp_15_reg_337 <= switches[32'd5];
        tmp_16_reg_342 <= switches[32'd6];
        tmp_17_reg_347 <= switches[32'd7];
        tmp_reg_317 <= switches[32'd1];
        trunc_ln42_reg_312 <= trunc_ln42_fu_128_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_mix_out_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_mix_out_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_mix_out_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        mix_out_TDATA_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TDATA;
    end else begin
        mix_out_TDATA_int_regslice = mix_out_TDATA_reg;
    end
end

always @ (*) begin
    if (((grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        mix_out_TKEEP_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TKEEP;
    end else begin
        mix_out_TKEEP_int_regslice = mix_out_TKEEP_reg;
    end
end

always @ (*) begin
    if (((grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        mix_out_TLAST_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TLAST;
    end else begin
        mix_out_TLAST_int_regslice = mix_out_TLAST_reg;
    end
end

always @ (*) begin
    if (((grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        mix_out_TSTRB_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TSTRB;
    end else begin
        mix_out_TSTRB_int_regslice = mix_out_TSTRB_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_in_TREADY_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_stream_in_TREADY;
    end else begin
        stream_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_mix_out_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln44_fu_208_p2 = (select_ln43_1_fu_200_p3 + 2'd1);

assign add_ln45_fu_226_p2 = (zext_ln45_fu_222_p1 + 3'd1);

assign add_ln46_fu_240_p2 = (select_ln45_fu_232_p3 + 3'd1);

assign add_ln47_fu_254_p2 = (select_ln46_fu_246_p3 + 3'd1);

assign add_ln48_fu_268_p2 = (select_ln47_fu_260_p3 + 3'd1);

assign add_ln49_fu_290_p2 = (zext_ln49_fu_287_p1 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_start = grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_ap_start_reg;

assign grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TREADY = (mix_out_TREADY_int_regslice & ap_CS_fsm_state3);

assign mix_out_TVALID = regslice_both_mix_out_V_data_V_U_vld_out;

assign mix_out_TVALID_int_regslice = grp_mixer_Pipeline_VITIS_LOOP_27_1_fu_94_mix_out_TVALID;

assign select_ln43_1_fu_200_p3 = ((tmp_fu_132_p3[0:0] == 1'b1) ? select_ln43_fu_192_p3 : zext_ln43_fu_188_p1);

assign select_ln43_fu_192_p3 = ((trunc_ln42_fu_128_p1[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign select_ln44_fu_214_p3 = ((tmp_12_fu_140_p3[0:0] == 1'b1) ? add_ln44_fu_208_p2 : select_ln43_1_fu_200_p3);

assign select_ln45_fu_232_p3 = ((tmp_13_fu_148_p3[0:0] == 1'b1) ? add_ln45_fu_226_p2 : zext_ln45_fu_222_p1);

assign select_ln46_fu_246_p3 = ((tmp_14_fu_156_p3[0:0] == 1'b1) ? add_ln46_fu_240_p2 : select_ln45_fu_232_p3);

assign select_ln47_fu_260_p3 = ((tmp_15_fu_164_p3[0:0] == 1'b1) ? add_ln47_fu_254_p2 : select_ln46_fu_246_p3);

assign select_ln48_fu_274_p3 = ((tmp_16_fu_172_p3[0:0] == 1'b1) ? add_ln48_fu_268_p2 : select_ln47_fu_260_p3);

assign stream_in_TREADY = regslice_both_stream_in_V_data_V_U_ack_in;

assign tmp_12_fu_140_p3 = switches[32'd2];

assign tmp_13_fu_148_p3 = switches[32'd3];

assign tmp_14_fu_156_p3 = switches[32'd4];

assign tmp_15_fu_164_p3 = switches[32'd5];

assign tmp_16_fu_172_p3 = switches[32'd6];

assign tmp_fu_132_p3 = switches[32'd1];

assign trunc_ln42_fu_128_p1 = switches[0:0];

assign zext_ln43_fu_188_p1 = trunc_ln42_fu_128_p1;

assign zext_ln45_fu_222_p1 = select_ln44_fu_214_p3;

assign zext_ln49_fu_287_p1 = select_ln48_reg_352;


reg find_kernel_block = 0;
// synthesis translate_off
`include "mixer_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //mixer

